### ISSUE TITLE
documentation should give path

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nrpe#100]
At the end of `make all` you get

> Read the PDF documentation (NRPE.pdf) for information on the next steps you should take to complete the installation or upgrade.

It would be better to say 
> Read the PDF documentation (included in your current directory at docs/NRPE.pdf) for information on the next steps you should take to complete the installation or upgrade.

If that is thought to be too long, then 
> Read the PDF documentation (docs/NRPE.pdf) for information on the next steps you should take to complete the installation or upgrade.

would be preferred

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nrpe/commit/f94112bb61c6b60045ed6efb9263c08b8cb0f070
