### ISSUE TITLE
documentation needs to be updated

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nrpe#101]
Currently, the documentation included is from 2 June 2016. However, the current documentation is from 4 January 2017.

**Comment by jfrickson** [comment]
@douglasawh What doc is from 2016?

**Comment by douglasawh** [comment]
2016: https://github.com/NagiosEnterprises/nrpe/blob/master/docs/NRPE.pdf
2017: https://assets.nagios.com/downloads/nagioscore/docs/nrpe/NRPE.pdf

**Comment by jfrickson** [comment]
Updated in branch `maint`.
