### ISSUE TITLE
Ability to restrict unbounded growth for nrpe processes.

### ISSUE THREAD

**Issue by meabandit** [NagiosEnterprises/nrpe#104]
It would be nice to be able to limit the amount of worker processes via configuration file similar to the way check_workers is used in Nagios Core.

**Comment by hedenface** [comment]
I think this is a good idea. We'll talk about it at our next internal open source development meeting.

**Comment by hedenface** [comment]
This isn't anything super advanced like httpd's scoreboard. But it does keep track of how many forks exist, won't let you go over it (via a basic while/sleep loop), and logs WARNING level if choked.

Added via https://github.com/NagiosEnterprises/nrpe/commit/42ce4afa86788b3028a5084ab4cf6b3c9b2e0613
