### ISSUE TITLE
Update the nrpe.cfg file and add the common.cfg and asterisk.cfg to the installer.

### ISSUE THREAD

**Issue by tgriep** [NagiosEnterprises/nrpe#106]
Add the same configurations files that the Linux Agent Installer (Version 2.15) uses so when the new agent is installed, the predefined commands will be compatible with Nagios XI's wizards.

**Comment by jfrickson** [comment]
Looking into this.

**Comment by hedenface** [comment]
This is a good idea. Added for 3.2.0

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nrpe/commit/d765d62f76daf8fc8edd0fae16a2790452e42c9a

These are turned off by default, but they mimic those found in the linux-nrpe-agent tarball all in nrpe.cfg.in
