### ISSUE TITLE
Add a note to nrpe.cfg about log_facility

### ISSUE THREAD

**Issue by meabandit** [NagiosEnterprises/nrpe#107]
The current install nrpe.cfg lists this text:
```
# LOG FACILITY
# The syslog facility that should be used for logging purposes.

log_facility=daemon
```
vs
```
# PORT NUMBER
# Port number we should wait for connections on.
# NOTE: This must be a non-priviledged port (i.e. > 1024).
# NOTE: This option is ignored if NRPE is running under either inetd or xinetd

server_port=5666
```
log_facility is also ignored when running under xinetd so another note in the file about that would be helpful.

**Comment by jfrickson** [comment]
I just changed my nrpe to run under xinetd, and set `log_facility=auth` in nrpe.cfg. I then ran `./check_nrpe -H 127.0.0.1` and nrpe messages in syslog came across as `auth`.

Is there a forum post behind this request?

**Comment by jfrickson** [comment]
Unable to reproduce.
