### ISSUE TITLE
Custom log is not created when NRPE is running under xinetd

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nrpe#109]
I specified a custom log file in the nrpe.cfg:

```
# LOG FILE
# If a log file is specified in this option, nrpe will write to
# that file instead of using syslog.

#log_file=${prefix}/var/nrpe.log
log_file=/usr/local/nagios/var/nrpe.log

```

and restarted xinetd. The "nrpe.log" never got created, and I can see that logging is still done in "/var/log/messages".

Note: I can verify that the same setting works when NRPE is running as a standalone daemon (not under xinetd)

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nrpe/commit/6b5a9b688de3a0b3e4a9085b33e24ae26c32d091

Will be in release 3.1.1
