### ISSUE TITLE
Help output is misleading

### ISSUE THREAD

**Issue by sreinhardt** [NagiosEnterprises/nrpe#11]
The help output from nrpe -h does not provide the correct usage for config files. The usage line states:

Usage: nrpe [-n] -c <config_file> [-4|-6] <mode>

Whereas the options section does not list -c <config_file>:

Options:
 -n            = Do not use SSL
 <config_file> = Name of config file to use

Not a big deal, but would be nice to resolve.

**Comment by tmcnag** [comment]
Pull it

**Comment by jfrickson** [comment]
Commit https://github.com/NagiosEnterprises/nrpe/commit/b62ca7415f7fbf8c57576b441bbe32bbb73bc4f2 pulled this into branch https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC1
