### ISSUE TITLE
The '-g' option creates a log file but nothing gets written to it

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nrpe#111]
If you try to use the '--log-file=' or '-g' option with check_nrpe, the log file specified gets created, but nothing gets written to it.

Example:

`# /usr/local/nagios/libexec/check_nrpe -H x.x.x.x -g /usr/local/nagios/var/nrpe.log`

```
# ls -la /usr/local/nagios/var/nrpe.log
-rw-r--r-- 1 nagios nagios 0 Apr 18 12:55 /usr/local/nagios/var/nrpe.log
# file /usr/local/nagios/var/nrpe.log
/usr/local/nagios/var/nrpe.log: empty
```

Tested with NRPE running under xinetd.

**Comment by jfrickson** [comment]
Should there have been something? Try adding (or removing) the `-n` to force something that would get logged, or add `-s 1` for SSL logging.

**Comment by jfrickson** [comment]
The code to open the log file now occurs earlier (see issue #109). But it's entirely possible to have the log file created, but empty.
