### ISSUE TITLE
check_nrpe = segfault when specifying a config file

### ISSUE THREAD

**Issue by Worst45** [NagiosEnterprises/nrpe#112]
I installed the 'testing' version of nagios-nrpe-plugin in Debian 8 (v3.0.1-3 amd64), and the equivalent testing version of 'nagios-nrpe-server' on another host (also in v3.0.1-3 amd64) (to use the new SSL features and prevent old/insecure ciphers)

When I try to connect to the server with '-f' option (to specify SSL limitations), I get a segfault. This can be reproduced **even when the config file is empty**:
```
# /usr/lib/nagios/plugins/check_nrpe -H 192.168.x.y -f /etc/nagios3/nrpe.cfg
Erreur de segmentation       (Segmentation fault, in French)
```

No connection is made to the server (I activated debug output just to be sure, and no syslog event)

If I remove the '-f' flag, I get an SSL error that I will submit in another issue :)

Some details:
```
# /usr/lib/nagios/plugins/check_nrpe -V

NRPE Plugin for Nagios
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 3.0.1
Last Modified: 09-08-2016
License: GPL v2 with exemptions (-l for more info)
SSL/TLS Available: OpenSSL 0.9.6 or higher required
```

My Debian is a stable version, in 8.7, with official packages

**Comment by jfrickson** [comment]
How do you get the testing versions of packages?

**Comment by jfrickson** [comment]
Never mind, I figured it out. Checking now.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nrpe/commit/888ad6b5b4709ed0627ef4f04274ab13088000de

Will be in release 3.1.1.
