### ISSUE TITLE
nrpe daemon doesn't log client IP address

### ISSUE THREAD

**Issue by sebastic** [NagiosEnterprises/nrpe#115]
As reported by Ralf G. R. Bergs in [Debian Bug #860802](https://bugs.debian.org/860802):
> I'm seeing scans from hosts on the internet like follows:
> 
> 2017-04-17T06:27:33.100900+00:00 myhost nrpe[7751]: Error: Request
> packet type/version was invalid!
> 2017-04-17T06:27:33.100902+00:00 myhost nrpe[7751]: Client request was
> invalid, bailing out...
> 
> It would be very important to see the client's address, so that you
> can tell whether it's "hammering" by a single IP, or a distributed
> scan, and to also block these IPs.
> 
> Thanks for considering to include this in a future version.

**Comment by jfrickson** [comment]
Since version 3.0.0, the line for the second log message is:
```
logit(LOG_ERR, "Client request from %s was invalid, bailing out...", remote_host);
```
and will therefor log the remote host.
