### ISSUE TITLE
Unable to compile nrpe-3.1.0 - undefined references to va_start, va_end

### ISSUE THREAD

**Issue by karlos1841** [NagiosEnterprises/nrpe#116]
I cannot compile nrpe-3.1.0 due to "undefined reference" error to va_start, va_end in utils.c.
Apparently, these functions are defined in stdarg.h but I have not seen it included anywhere in utils.h or anywhere in "include" directory.

**Comment by jfrickson** [comment]
nrpe.c includes acl.h which includes stdarg.h so I'm going to assume compiling nrpe works, but check_nrpe fails. Is that correct?

**Comment by jfrickson** [comment]
Should be fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nrpe/commit/6ee49d8cb4f6dcc7d12fd11b107a0acfe0ce581d
Post a comment here if it's still not working.
Will be in version 3.1.1
