### ISSUE TITLE
error: line 42: Illegal char '-' in: Version: 3.1.0-rc1 

### ISSUE THREAD

**Issue by kaushalshriyan** [NagiosEnterprises/nrpe#118]
Hi, 

I did git clone https://github.com/NagiosEnterprises/nrpe.git on CentOS Linux release 7.3.1611 (Core) 

[root@localhost nrpe]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@localhost nrpe]#
[root@localhost nrpe]# pwd
/opt/nrpe
[root@localhost nrpe]# rpmbuild -ba nrpe.spec
**error: line 42: Illegal char '-' in: Version: 3.1.0-rc1**
[root@localhost nrpe]#

nrpe.spec file is described here -> http://sprunge.us/OWcR?eng

**Comment by jfrickson** [comment]
The problem comes from my forgetting to remove the `-rc1`. I'm automating the release process, and didn't verify this part. Will be fixed in 3.1.1.

**Comment by kaushalshriyan** [comment]
#./update-version 3.1.0
#autoconf
#./configure
#rpmbuild -ba nrpe.spec

/usr/bin/install -c -m 644 -o nagios -g nagios sample-config/nrpe.cfg /root/rpmbuild/BUILDROOT/nrpe-3.1.0-1.x86_64/etc/nagios
No init file to install`
make: *** [install-init] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.uT8bbi (%install)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.uT8bbi (%install)

Details of  **rpmbuild -ba nrpe.spec** -> http://sprunge.us/PVdG?eng

**Comment by jfrickson** [comment]
In the detail at lines 212-216 it says:
```
212 + ./configure '--with-init-type=%{_init_type}' --with-nrpe-port=5666 --with-nrpe-user=nagios --with-nrpe-group=nagios --prefix=/usr --exec-prefix=/usr/sbin --bindir=/usr/sbin --sbindir=/usr/lib/nagios/cgi --libexecdir=/usr/lib/nagios/plugins --datadir=/usr/share/nagios --sysconfdir=/etc/nagios --localstatedir=/var/log/nagios --enable-command-args
213 checking for a BSD-compatible install... /usr/bin/install -c
214 checking what the operating system is ... linux
215 checking what the distribution type is ... rhel
216 checking what init system is being used ... %{_init_type}
```
It looks like the init type is not being set properly.

**Comment by kaushalshriyan** [comment]
Hi John,

I am running CentOS Linux release 7.3.1611 (Core)

[root@localhost ]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@localhost ]#

Do i need to do any changes on the linux box for init type is not being set
properly. Not sure if i understand the issue completely. Please suggest.

Regards,

Kaushal

**Comment by jfrickson** [comment]
Ok, I see the problem.

The file `nrpe.spec.in` (and the file created from it -- `nrpe.spec`) have an error on line 12:
```
%define _init_tyhpe @init_type@
```
It should be:
```
%define _init_type @init_type@
```
I've fixed it in the current 'maint' branch.

**Comment by kaushalshriyan** [comment]
It worked now and the details http://sprunge.us/aAgY?eng

**Comment by jfrickson** [comment]
Great! I'll close this issue then.
