### ISSUE TITLE
Bug - Client certificate setup still logs 'SSL Client X.X.X.X has an invalid certificate' even when it's working properly

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nrpe#123]
Bug - Client certificate setup still logs 'SSL Client X.X.X.X has an invalid certificate' even when it's working properly.

Apparently those messages are informational and an actual failure would send a different message. When you format the informational message, it gets the validity wrong.

As a workaround, they can turn off the ssl_logging flag to skip just that message in both ends:

`#         0x10 (26) = Log if client has a certificate`

**Comment by jfrickson** [comment]
Calls to `SSL_get_verify_result()` are resulting in "invalid" instead of "valid" when it should be "valid". The `preverify_ok` parameter passed to `verify_callback()` does have the correct value. My `SSL_get_verify_result()`  check must be faulty, somehow.

**Comment by hedenface** [comment]
Added for 3.1.2

**Comment by hedenface** [comment]
SSL_get_verify_result() checks against X509_V_OK which is actually a falsy return unless checked explicitly. Fixed in https://github.com/NagiosEnterprises/nrpe/commit/51a264813d4a8c3a7e74da8191d69fd8c67dcfe3
