### ISSUE TITLE
Discussion: NRPE and Anonymous Diffie Hellman

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nrpe#124]
I wanted to start a discussion on this now as before too long it will start to affect end users and we should develop some strategies on how to deal with the problem.

As per: https://github.com/NagiosEnterprises/nrpe/commit/dc3637f64cedac07197fbc9936022578f9f44855

Anonymous Diffie Hellman is not available in OpenSSL 1.1.x so if there's no certificates, it ends up with a "no shared cipher" error. If you aren't aware how NRPE client works, basically an anonymous SSL handshake is used to encrypt traffic. It allows encryption without certificates.

Once the various Linux operating systems start distributing OpenSSL 1.1.x we should expect to see problems. We are already seeing this arise with the bleeding edge distributions like Arch Linux https://github.com/NagiosEnterprises/nrpe/issues/119.

My experience so far has been that if the nrpe client has the issue, there are two solutions:

Configure daemon to run without SSL by defining the -n argument in the daemon service
- Requires check_nrpe client to also use the -n argument
- The check_nrpe client to will not be able to just use the -n argument alone, the daemon also requires it
- Can also be compiled with --disable-ssl and this negates the need for the -n argument

Configure daemon to run using SSL/TLS certificates
- the client and check_nrpe require certificates (need to clarify if only one end is required, not both)
- NRPE client can use a certificate for encryption
- The NRPE client can request the check_nrpe plugin provide a valid certificate
- https://support.nagios.com/kb/article/nrpe-v3-enhanced-security.html

Either solution requires changes to be made on both ends.

Creating certificates manually really adds a lot more work to the whole "build from source" process. I think we should look at adding some arguments to the configure command to automatically create certificates and implement them in the nrpe.cfg file. Perhaps also create a certificate for check_nrpe and provide a config file for check_nrpe. This will allow for a more automated build process.

What are your thoughts on this?

**Comment by sebastic** [comment]
Generating certificates must not be part of the build, because for binary packages the certificate will be identical for all installations, which is a problem that long plagued the security of NRPE.

A helper script that generates the certificates could be installed alongside `nrpe` & `check_nrpe`, and optionally called as part installation process. Binary packages can use that script in their post install scripts to generate the certificates on the systems where the package is installed.

**Comment by box293** [comment]
Good point. So perhaps something like:
Create a common CA:
```
make cert-ca
```
Create a cert for the Daemon:
```
make cert-init
```
Create a cert for the check_nrpe plugin:
```
make cert-plugin
```
And then perhaps some extra commands to:

- update config file in `nrpe.cfg` to point to cert and define `ssl_client_certs=2`
- create config file for check_nrpe to point to cert

**Comment by sebastic** [comment]
If the `Makefile` calls the helper script that should be fine, binary packages generally don't include the `Makefile` which is only used for the build.

**Comment by jfrickson** [comment]
I'll try for 3.2.0, but not making any promises ;-)

**Comment by tmcnag** [comment]
I think Troy is right, and that cert-based is vastly preferred over everyone sending in plain-text.  The binary package problem is definitely a hurdle, but Apache is also provided as a binary and people still have to generate (or purchase) their own certs, so this is no different.

**Comment by hedenface** [comment]
# Our official stance is going to be the usage of public/private keys.

I did however commit a fix in maint via https://github.com/NagiosEnterprises/nrpe/commit/99b0de98cbf5ea1449a6d5add85eca9ec7fcbe63 that will allow people to continue using anonymous if they wish - I'm going to add a flag for this in the next enhancement release, similar to `dont_blame_nrpe` or maybe even a `./configure` flag that ensures that they know they are enabling a very insecure method of transport. I'm closing the issue as I consider this issue resolved. If there is to be more discussion, please re-open and comment.

**Comment by box293** [comment]
I think we still need to automate the creation of certificates as this can be a somewhat time consuming process.

**Comment by hedenface** [comment]
I don't particularly agree, @box293 - As @tmcnag said previously:

> but Apache is also provided as a binary and people still have to generate (or purchase) their own certs, so this is no different.

This is actually no different than any other binary that is distributed that requires certificates. There are plenty of applications like easy-rsa and certbot that can generate certificates quickly and efficiently. Why should we spend both time and money to re-invent the wheel (and debug and maintain it)?

That being said, there is a `contrib/` folder, and anyone is welcome to make the script, issue a pull request, and I'll make sure it gets included.

**Comment by jsteel44** [comment]
I'm not on a particular side here, but I don't think this is the same as Apache; with this change we are pulling the rug out from users who've had a working NRPE SSL setup. This CAN be the same as Apache but we need a clear upgrade path for users/distributions and I don't think that should be "DIY".

**Comment by hedenface** [comment]
@jsteel44 I do understand, but keep in mind that the anonymous SSL method will remain in existence. We aren't removing it entirely, just trying to make users more aware of it's insecurities.

I wouldn't say that we're pulling the rug out from anyone, we're reacting to a change that has occured and will continue to occur on a grander scheme in the following year I'm sure. Figuring this all out now is a Good Thing.

Moreover, my worries are purely economical. There are better suited paths for certificate management - it's one thing to make a simple script that creates a certificate and self-signs it, it's another thing to make sure it works on every system and spend time debugging it when it goes wonky.

I agree that a clear path needs to be distinguished here. I would just prefer that that path includes using some other certificate management software.

**Comment by box293** [comment]
If you look at NCPA it automatically generates certificates and implements them as part of the install. Perhaps we can see how it is being done there.

**Comment by hedenface** [comment]
Okay, this time for real I am closing the issue. @box293 We will look into perhaps including a very basic script in an upcoming release - but since I left the ADH stuff as is and the defaults the same, this is something that needs to be brought up at the next Nagios OSS meeting. It is on the list, and a priority - so I'll either update this issue (maybe not I might forget) or I will just make the changes and apply them to the readme(s).

Thanks for your input everyone.
