### ISSUE TITLE
Problem compiling NRPE 3.1 on CentOS

### ISSUE THREAD

**Issue by cbbs70a** [NagiosEnterprises/nrpe#125]
All;
I am trying to upgrade nrpe to version 3.1 on CentOS 5 systems. I know, I know, CentOS 5 is ancient, but unfortunately, I cannot upgrade them. I upgraded openssl to version 1.0.2.l. First I do a "configure --enable-command-args --with-ssl=/usr/local/ssl", then a "make nrpe". I am getting the following errors. Any help at all would be greatly appreciated.
Thanks;
FSD
```
cd ./src/; make
make[1]: Entering directory `/usr/local/src/nrpe-3.1.0/src'
gcc -g -O2 -I/usr/include/krb5 -I/usr/kerberos/include -DHAVE_CONFIG_H -I ../include -I ./../include -o nrpe ./nrpe.c ./utils.c ./acl.c -L/usr/kerberos/lib64 -lssl -lcrypto -ldl -lz -lnsl -lwrap
./nrpe.c: In function 'init_ssl':
./nrpe.c:316: warning: passing argument 1 of 'SSL_CTX_new' discards qualifiers from pointer target type
./nrpe.c:362: error: 'SSL_OP_NO_TLSv1_1' undeclared (first use in this function)
./nrpe.c:362: error: (Each undeclared identifier is reported only once
./nrpe.c:362: error: for each function it appears in.)
./utils.c: In function 'open_log_file':
./utils.c:479: error: 'O_NOFOLLOW' undeclared (first use in this function)
./utils.c:479: error: (Each undeclared identifier is reported only once
./utils.c:479: error: for each function it appears in.)
make[1]: *** [nrpe] Error 1
make[1]: Leaving directory `/usr/local/src/nrpe-3.1.0/src'
make: *** [nrpe] Error 2
```

**Comment by jfrickson** [comment]
That's strange. The only place `SSL_OP_NO_TLSv1_1` gets used, there's an `#ifdef` wrapper:
```
#ifdef SSL_OP_NO_TLSv1_1
			ssl_opts |= SSL_OP_NO_TLSv1_1;
#endif
```
Try using version 3.1.1 (https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.1.1/nrpe-3.1.1.tar.gz) and see if that works any better.

**Comment by cbbs70a** [comment]
Thanks for the quick response. I downloaded 3.1.1 and I was able to get it to compile. Can't thank you enough.
Regards;
FSD
