### ISSUE TITLE
nrpe 3.1.1 overrides configuration settings for ssl cert and key files

### ISSUE THREAD

**Issue by cbbs70a** [NagiosEnterprises/nrpe#127]
Hello;
    I am using nrpe 3.1.1 and I have set the following values in nrpe.cfg:  ssl_cacert_file, ssl_cert_file, and ssl_privatekey_file to a custom location. However, in the debug file, I see errors saying nrpe could not find the ssl files in the /etc/ssl/servercerts directory, regardless of the values that I set. When I move the ssl files to the default directory above, the problem goes away.
Thanks Much;
 FSD

**Comment by box293** [comment]
Can you show us the values in `nrpe.cfg` for the options `ssl_cacert_file`, `ssl_cert_file` and `ssl_privatekey_file`.

**Comment by cbbs70a** [comment]
Sorry, I'm not sure why it was not working before, but I cannot duplicate the error now. My bad. Thanks for your help.
Regards;
Frank
