### ISSUE TITLE
Logging done to wrong place if log_file option not at top of nrpe.cfg

### ISSUE THREAD

**Issue by heaje** [NagiosEnterprises/nrpe#129]
I'm in a situation where I really don't want to modify the nrpe.cfg file.  Instead, I make local changes in files in the /etc/nrpe.d/ directory (which nrpe.cfg includes).  In my local change file (let's call it 01_local.cfg) I need to specify a new log file:

```
log_file=/var/log/nrpe/nrpe.log
```

The problem with this is that as nrpe.cfg is read, any errors or issues will show up in Syslog until AFTER my local config has been read.  This means my log_file parameter is basically only used when debug is on.  Is there a way to make NRPE send all logs to my defined log file regardless of when the entry shows up in the configs?

**Comment by jfrickson** [comment]
That would require reading ahead, which would slow down the startup process.

You will either have to add the `log_file` directive at the top of your `nrpe.cfg`, or have an entry at the top, something like `include_file=/etc/nrpe.d/first.cfg` which would have the `log_file` directive.

Sorry, that's the best I can do.
