### ISSUE TITLE
Missing xinetd installation option in make for NRPE 3

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/nrpe#130]
Previously in NRPE 2.15 there was a xinetd file that was placed in `/etc/xinetd.d/` during installation when running the make option `install-xinetd` but that option no longer exists. This means that you have to write your own xinetd file.

I tried using `install-inetd` but it did not detect xinetd and did not install.

**Comment by hedenface** [comment]
Added to 3.1.2

**Comment by hedenface** [comment]
Confirmed for Cent6. Works on Cent7 strangely enough.

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nrpe/commit/a6b8455427a7180077be14bd92c6c53ba001b518
