### ISSUE TITLE
Unrecognized --version and -v on nrpe binary

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/nrpe#131]
When running `-v` or `--vesrion` on the nrpe binary, it gives an error:

```
/usr/local/nagios/bin/nrpe: unrecognized option '--version'
```

It would be nice to have a flag to output the current version

**Comment by hedenface** [comment]
Added for 3.2.0

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nrpe/commit/3b12d314e0712d182b2e7b0296df7af370eb5466
