### ISSUE TITLE
check_nrpe: option to write errors in stdout instead stderr

### ISSUE THREAD

**Issue by garnier-quentin** [NagiosEnterprises/nrpe#132]
Hi,

An option to write errors in stdout would be be great.

**Comment by hedenface** [comment]
Is there a problem specifically with redirecting stderr to stdout? via something like `2>&1`? Not saying it's a bad idea - we'll definitely review it - but this kind of functionality is built directly into most modern OSes.

**Comment by garnier-quentin** [comment]
Yes. I could add it in command line. In NRPE, you use a shell before the execution ? 
Moreover, some messages are from NRPE daemon itself. So i can't redirect it.

**Comment by hedenface** [comment]
Are you able to supply some specific examples of where you'd like stderr redirected to stdout?

**Comment by garnier-quentin** [comment]
For example:
```
/usr/lib64/nagios/plugins/check_nrpe -H 127.0.0.1 
connect to address 127.0.0.1 port 5666: Connection refused
connect to host 127.0.0.1 port 5666: Connection refused
```

**Comment by hedenface** [comment]
In that particular case, then appending the `2>&1` at the end sends it directly to stdout. How about the daemon example?

**Comment by garnier-quentin** [comment]
Yes you're right. It always be chek_nrpe will do the stderr. But if you have plugin stderr only, the error message is 'Unable to read the output'.

**Comment by hedenface** [comment]
Which is somewhat accurate, I suppose. What if we adjust the return code to be UNKNOWN while we're at it? Since that would make a bit more sense as well.

**Comment by garnier-quentin** [comment]
The 'UNKNOWN' is great. But we don't really know what happened. We need to execute the plugin on distant server to see the stderr.

**Comment by hedenface** [comment]
> But we don't really know what happened

That's kind of what UNKNOWN means, right? :)

Okay, we'll talk about it at the next meeting we have here, it's listed for review and scheduled for the next enhancement release.

**Comment by garnier-quentin** [comment]
With "Unable Read Output" and 'UNKNOWN', it's ok for me.

**Comment by hedenface** [comment]
@garnier-quentin What version of nrpe are you on? I spent a few minutes looking for anywhere where it even prints to stderr, and there is only one location in the current codebase:

    fprintf(stderr, "setsockopt IPV6_V6ONLY: %s", strerror(errno));

This is not the output you're reporting. Perhaps you can put together a walkthrough for me to duplicate your output entirely?

**Comment by hedenface** [comment]
Hmm. My mistake. I'll add this in. I see where the issue lies I think. We'll just get it in for 3.2.0.

**Comment by hedenface** [comment]
Also, something to keep in mind - the value you set for timeout_return_code is what is used for this return value. ***I will not change that***. But we can add an option for printing the connection info to stdout instead.

**Comment by hedenface** [comment]
Added in https://github.com/NagiosEnterprises/nrpe/commit/10df3aa02b58c4acef87012b09476571317dc631
