### ISSUE TITLE
illegal_metachar value setup seems uneffective

### ISSUE THREAD

**Issue by Sims24** [NagiosEnterprises/nrpe#134]
Hi, 

I face an issue where I need to pass some "{" and "}" in some args of my check command. I tried to modify the value of illegal_metachar config value and restart my daemon but looks like my server just ignore it ... 

Illegal metachar definition : 

`illegal_metachar=`|[];`

Sample commande that doesn't work : 

`/usr/lib64/nagios/plugins/check_nrpe -H 127.0.0.1 -c check_dummy_metachar -a ' --option "%{down}  > 4"' `

Output : 

`CHECK_NRPE: Receive header underflow - only 0 bytes received (4 expected).`

Log trace : 

```
Jun 21 14:07:31 ucs1 nrpe[1086]: Error: Request contained illegal metachars!
Jun 21 14:07:31 ucs1 nrpe[1086]: Client request from 127.0.0.1 was invalid, bailing out...
```

Did I miss something regarding NRPEv3 server implementation ?
Thanks
Simon

**Comment by hedenface** [comment]
I'll test this soon, and add label for Bug as it sits. I'll update when I have more information.

**Comment by Sims24** [comment]
After digging around config key has changed it's now nasty_metachars instead of illegal_metachar. You can remove bug tag I think ... Sorry for that :)

**Comment by raghuveerp** [comment]
What was the solution/resolution for this ? I am hitting the same error. Can you please suggest how to fix it ?
