### ISSUE TITLE
 ERROR: my_system() seteuid(0): Operation not permitted, bailing out...

### ISSUE THREAD

**Issue by SundanceRaphael** [NagiosEnterprises/nrpe#139]
Definition 
-> monitor server = the server which run nagios (NRPE  v 3.2.0 is installed)
-> client = server that should monitored (NRPE  v 3.2.0 is installed)

After upgrading from 3.1.1 to 3.2.0 
Configuration: 
-> TLSv1.2+ is on

Certificate Validation seams ok.

The monitorserver gets following error: 
NRPE: Unable to read output 

The client log shows:
```
[1498553716] Host 10.0.0.23 is asking for command 'check_users' to be run...
[1498553716] Running command: /usr/local/nagios/libexec/check_users -w 1 -c 2
[1498553716] ERROR: my_system() seteuid(0): Operation not permitted, bailing out...
[1498553716] Command completed with return code 2 and output:
[1498553716] Return Code: 3, Output: NRPE: Unable to read output
[1498553716] Connection from XXX.XXX.XXX closed.
```

Same error for configuration with command line arguments and for with out.

Execute command on local machine is OK (Except the fact that it should be in critical mod... but not relevant on this issue)
```
 /usr/local/nagios/libexec/check_users -w 1 -c 2
USERS WARNING - 2 users currently logged in |users=2;1;2;0
```

Configuration file ./configure
```
checking for struct sockaddr_storage... yes
checking for seteuid... yes
checking for va_copy... yes
checking for vsnprintf... yes
```

Seams to be seteuid(0) get an -1 check with the error message is in src/nrpe.c Line 2224 and 2497

Following Upgrades were done 2.15 -> 3.1.1 -> 3.2.0
Plugin Version: 2.2.1
NRPE Version 3.2.0
Nagios Version 5.4.5
OS Monitoring Server: CentOS 6.9
OS client: Ubuntu 16.04.2

Can you assist to get it running?

**Comment by hedenface** [comment]
Looking into it now, but it's likely an issue with permissions. The `seteuid()` code wasn't actually changed - the difference is that now it checks the result instead of just assuming it returned fine.

Are any other checks failing? Let's see the permissions of `/usr/local/nagios/libexec/check_users` please.

**Comment by SundanceRaphael** [comment]
All standard host tests from Nagiosxi fails in the same way (e.g.: check_disk)
 /usr/local/nagios/libexec/check_nrpe -H 10.0.0.36 (TSL/SSL credantials sended (-A, -K -C) )
 /usr/local/nagios/libexec/check_nrpe -H 10.0.0.36 -V (TSL/SSL credantials sended (-A, -K -C) )

Downgrate to 3.1.1 checks running again with known issue Bug - Client certificate setup still logs 'SSL Client X.X.X.X has an invalid certificate' even when it's working properly #123

**Comment by hedenface** [comment]
@SundanceRaphael I am very sorry, but I am not understand what you're talking about here. The invalid certificate issue has nothing to do with the ticket you opened, or are you somehow thinking these are related?

So you're saying that **all** checks from your Nagios XI (Cent 6.9) that route via NRPE to the client (10.0.0.36 / Ubuntu 16.04) are failing?

May I please see the permissions of every plugin in your `/usr/local/nagios/libexec` or similar directory on the Ubuntu client, please?

**Comment by SundanceRaphael** [comment]
Sorry the confusion.
I say that test from NagiosXi and from comandline to the client are failing with the error message using NRPE 3.2.0. 
I do not know wheter the invalid certificate issue is related or not.

Bug #123 seems fixed from what I see in the logs using NRPE 3.2.0.
In the logging mod ssl_logging=0x01 it is the last entry before the error entry in the log.
The client log snippet, as shown above in my opening comment in this issue, is in mod ssl_logging=0x2f.
I can post the /usr/local/nagios/libexec tommorow morning (German time (MESZ)). I have no acces to the data at the momment.

The monitor server and client is set up according to
https://support.nagios.com/kb/article.php?id=519
and
https://support.nagios.com/kb/article.php?id=515

The nrpe is compiled without support for command arguments.

Test System before upgrading:
client (10.0.0.36) with NRPE 3.1.1
monitor server with NRPE 3.1.1
Test result with test system before upgrading:
* false positive "certifacte error" logged on client (see Bug #123)
* Checks succesfull

Test System after upgrading:
client (10.0.0.36) with NRPE 3.2.0
monitor server with NRPE 3.2.0
Test result with test system after upgrading:
* certifacte valid logged on client
* Checks fails with "ERROR: my_system() seteuid(0): Operation not permitted, bailing out..."

Test System after downgrading:
client (10.0.0.36) with NRPE 3.1.1
monitor server with NRPE 3.1.1
Test result with test system after downgrading:
* false positive "certifacte error" logged on client (see Bug #123)
* Checks succesfull

**Comment by hedenface** [comment]
Can I please see the permissions on your plugins in the plugins directory on the client?

**Comment by hedenface** [comment]
Actually, this has been confirmed, and I am issuing a fix shortly.

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nrpe/commit/06f9781758e7682ed041335317c706d4c4d168c9

**Comment by SundanceRaphael** [comment]
Hello hedenface,

I can confirm that now the checks not fail anymore, but in ssl_logging still the error message occurs
ERROR: my_system() seteuid(0): Operation not permitted

Requested plugin permissions client
drwxrwxr-x 2 nagios nagios   4096 Jun 28 08:47 .
drwxr-xr-x 8 nagios nagios   4096 Jun 16 14:48 ..
-rwxr-xr-x 1 root   nagios 178028 Jun 16 14:48 check_apt
-rwxr-xr-x 1 root   nagios   6897 Jun 16 14:48 check_asterisk.pl
-rwxr-xr-x 1 root   nagios   1978 Jun 16 14:48 check_asterisk_sip_peers.sh
-rwxr-xr-x 1 root   nagios   2242 Jun 16 14:48 check_breeze
-rwxr-xr-x 1 root   nagios 182764 Jun 16 14:48 check_by_ssh
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_clamd -> check_tcp
-rwxr-xr-x 1 root   nagios 132228 Jun 16 14:48 check_cluster
-rwxr-xr-x 1 root   nagios   5582 Jun 16 14:48 check_cpu_stats.sh
-rwsr-xr-x 1 root   nagios 180956 Jun 16 14:48 check_dhcp
-rwxr-xr-x 1 root   nagios 195376 Jun 16 14:48 check_disk
-rwxr-xr-x 1 root   nagios   9289 Jun 16 14:48 check_disk_smb
-rwxr-xr-x 1 root   nagios  99908 Jun 16 14:48 check_dummy
-rwxr-xr-x 1 root   nagios   3349 Jun 16 14:48 check_file_age
-rwxr-xr-x 1 root   nagios   6315 Jun 16 14:48 check_flexlm
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_ftp -> check_tcp
-rwxr-xr-x 1 root   nagios 307656 Jun 16 14:48 check_http
-rwsr-xr-x 1 root   nagios 190608 Jun 16 14:48 check_icmp
-rwxr-xr-x 1 root   nagios 141184 Jun 16 14:48 check_ide_smart
-rwxr-xr-x 1 root   nagios  15123 Jun 16 14:48 check_ifoperstatus
-rwxr-xr-x 1 root   nagios  12600 Jun 16 14:48 check_ifstatus
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_imap -> check_tcp
-rwsr-xr-x 1 root   nagios    972 Jun 16 14:48 check_init_service
-rwxr-xr-x 1 root   nagios   6887 Jun 16 14:48 check_ircd
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_jabber -> check_tcp
-rwxr-xr-x 1 root   nagios 156688 Jun 16 14:48 check_ldap
lrwxrwxrwx 1 root   root       10 Jun 16 14:48 check_ldaps -> check_ldap
-rwxr-xr-x 1 root   nagios 153840 Jun 16 14:48 check_load
-rwxr-xr-x 1 root   nagios   5995 Jun 16 14:48 check_log
-rwxr-xr-x 1 root   nagios  21480 Jun 16 14:48 check_mailq
-rwxr-xr-x 1 root   nagios 141744 Jun 16 14:48 check_mrtg
-rwxr-xr-x 1 root   nagios 141120 Jun 16 14:48 check_mrtgtraf
-rwxr-xr-x 1 root   nagios 175180 Jun 16 14:48 check_mysql
-rwxr-xr-x 1 root   nagios 163556 Jun 16 14:48 check_mysql_query
-rwxr-xr-x 1 root   nagios 152868 Jun 16 14:48 check_nagios
-rwxr-xr-x 1 root   nagios  25602 Jun 16 14:48 check_netstat.pl
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_nntp -> check_tcp
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_nntps -> check_tcp
-rwxrwxr-x 1 nagios nagios 142864 Jun 28 08:47 check_nrpe
-rwxr-xr-x 1 root   nagios 184660 Jun 16 14:48 check_nt
-rwxr-xr-x 1 root   nagios 188504 Jun 16 14:48 check_ntp
-rwxr-xr-x 1 root   nagios 177648 Jun 16 14:48 check_ntp_peer
-rwxr-xr-x 1 root   nagios 170168 Jun 16 14:48 check_ntp_time
-rwxr-xr-x 1 root   nagios 210412 Jun 16 14:48 check_nwstat
-rwxr-xr-x 1 root   nagios   3290 Jun 27 15:44 check_open_files.pl
-rwxr-xr-x 1 root   nagios   8781 Jun 16 14:48 check_oracle
-rwxr-xr-x 1 root   nagios 159048 Jun 16 14:48 check_overcr
-rwxr-xr-x 1 root   nagios 170680 Jun 16 14:48 check_pgsql
-rwxr-xr-x 1 root   nagios 189436 Jun 16 14:48 check_ping
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_pop -> check_tcp
-rwxr-xr-x 1 root   nagios 186224 Jun 16 14:48 check_procs
-rwxr-xr-x 1 root   nagios 157256 Jun 16 14:48 check_real
-rwxr-xr-x 1 root   nagios   9581 Jun 16 14:48 check_rpc
-rwxr-xr-x 1 root   nagios   1455 Jun 16 14:48 check_sensors
-rwxr-xr-x 1 root   nagios   2174 Jun 16 14:48 check_services
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_simap -> check_tcp
-rwxr-xr-x 1 root   nagios   7599 Jun 16 14:48 check_sip
-rwxr-xr-x 1 root   nagios 241680 Jun 16 14:48 check_smtp
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_spop -> check_tcp
-rwxr-xr-x 1 root   nagios 155540 Jun 16 14:48 check_ssh
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_ssmtp -> check_tcp
-rwxr-xr-x 1 root   nagios 138596 Jun 16 14:48 check_swap
-rwxr-xr-x 1 root   nagios 230712 Jun 16 14:48 check_tcp
-rwxr-xr-x 1 root   nagios 156400 Jun 16 14:48 check_time
lrwxrwxrwx 1 root   root        9 Jun 16 14:48 check_udp -> check_tcp
-rwxr-xr-x 1 root   nagios 167688 Jun 16 14:48 check_ups
-rwxr-xr-x 1 root   nagios 132196 Jun 16 14:48 check_uptime
-rwxr-xr-x 1 root   nagios 130568 Jun 16 14:48 check_users
-rwxr-xr-x 1 root   nagios   2936 Jun 16 14:48 check_wave
-rwxr-xr-x 1 root   nagios    710 Jun 16 14:48 check_yum
-rwxr-xr-x 1 root   nagios   3435 Jun 16 14:48 custom_check_mem
-rwxr-xr-x 1 root   nagios    915 Jun 16 14:48 custom_check_procs
-rwxr-xr-x 1 root   nagios   4176 Jun 16 14:48 nagisk.pl
-rwxr-xr-x 1 root   nagios 128316 Jun 16 14:48 negate
-rwxr-xr-x 1 root   nagios 122768 Jun 16 14:48 urlize
-rwxr-xr-x 1 root   nagios   1864 Jun 16 14:48 utils.pm
-rwxr-xr-x 1 root   nagios   2791 Jun 16 14:48 utils.sh


Requested plugin permissions monitoring server

drwxrwsr-x 2 nagios nagios   4096 Jun 28 09:02 .
drwxr-xr-x 9 root   root     4096 May 31 19:02 ..
-rwxr-xr-x 1 root   nagios 183134 Jun 23 10:35 check_apt
-rwxrwxr-x 1 apache nagios   6897 May 31 19:02 check_asterisk.pl
-rwxrwxr-x 1 apache nagios   4173 May 31 19:03 check_bl
-rwxrwxr-x 1 apache nagios   2287 May 31 19:03 check_bpi.php
-rwxr-xr-x 1 root   nagios   2346 Jun 23 10:35 check_breeze
-rwxr-xr-x 1 root   nagios 185675 Jun 23 10:35 check_by_ssh
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_clamd -> check_tcp
-rwxr-xr-x 1 root   nagios 142010 Jun 23 10:35 check_cluster
-r-sr-xr-x 1 root   nagios 181663 Jun 23 10:35 check_dhcp
-rwxr-xr-x 1 root   nagios 195030 Jun 23 10:35 check_dig
-rwxrwxr-x 1 apache nagios   3861 May 31 19:02 check_dir
-rwxr-xr-x 1 root   nagios 196740 Jun 23 10:35 check_disk
-rwxr-xr-x 1 root   nagios   9469 Jun 23 10:35 check_disk_smb
-rwxr-xr-x 1 root   nagios 198367 Jun 23 10:35 check_dns
-rwxrwxr-x 1 apache nagios   8506 May 31 19:03 check_domain.php
-rwxr-xr-x 1 root   nagios  90214 Jun 23 10:35 check_dummy
-rwxrwxr-x 1 apache nagios   5576 May 31 19:03 check_em01.pl
-rwxrwxr-x 1 apache nagios  38345 May 31 19:03 check_email_delivery
-rwxrwxr-x 1 apache nagios  20511 May 31 19:03 check_email_delivery_epn
-rwxrwxr-x 1 apache nagios  20039 May 31 19:02 check_email_loop.pl
-rwxrwxr-x 1 apache nagios  82970 May 31 19:03 check_esx3.pl
-rwxr-xr-x 1 root   nagios   3860 Jun 23 10:35 check_file_age
-rwxr-xr-x 1 root   nagios   6504 Jun 23 10:35 check_flexlm
-rwxr-xr-x 1 root   nagios 187794 Jun 23 10:35 check_fping
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_ftp -> check_tcp
-rwxrwxr-x 1 apache nagios   3446 May 31 19:03 check_ftp_fully
-rwxr-xr-x 1 root   nagios 181893 Jun 23 10:35 check_hpjd
-rwxr-xr-x 1 root   nagios 362681 Jun 23 10:35 check_http
-r-sr-xr-x 1 root   nagios 191723 Jun 23 10:35 check_icmp
-rwxr-xr-x 1 root   nagios 149964 Jun 23 10:35 check_ide_smart
-rwxrwxr-x 1 apache nagios   1794 May 31 19:03 check_ifoperstatnag
-rwxr-xr-x 1 root   nagios  15275 Jun 23 10:35 check_ifoperstatus
-rwxr-xr-x 1 root   nagios  13423 Jun 23 10:35 check_ifstatus
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_imap -> check_tcp
-rwxrwxr-x 1 apache nagios  35413 May 31 19:03 check_imap_receive
-rwxrwxr-x 1 apache nagios  15576 May 31 19:03 check_imap_receive_epn
-rwxr-xr-x 1 root   nagios   6984 Jun 23 10:35 check_ircd
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_jabber -> check_tcp
-rwxr-xr-x 1 root   nagios 166870 Jun 23 10:35 check_ldap
lrwxrwxrwx 1 root   nagios     10 Jun 23 10:35 check_ldaps -> check_ldap
-rwxr-xr-x 1 root   nagios 163477 Jun 23 10:35 check_load
-rwxr-xr-x 1 root   nagios   6669 Jun 23 10:35 check_log
-rwxr-xr-x 1 root   nagios  22733 Jun 23 10:35 check_mailq
-rwxrwxr-x 1 apache nagios  66565 May 31 19:03 check_mongodb.py
-rwxrwxr-x 1 apache nagios  11876 May 31 19:03 check_mountpoints.sh
-rwxr-xr-x 1 root   nagios 148626 Jun 23 10:35 check_mrtg
-rwxr-xr-x 1 root   nagios 149871 Jun 23 10:35 check_mrtgtraf
-rwxrwxr-x 1 apache nagios  17546 May 31 19:03 check_mssql
-rwxrwxr-x 1 apache nagios  14446 May 31 19:03 check_mssql_database.py
-rwxrwxr-x 1 apache nagios  20473 May 31 19:03 check_mssql_server.py
-rwxr-xr-x 1 root   nagios 194421 Jun 23 10:35 check_mysql
-rwxrwxr-x 1 apache nagios 122024 May 31 19:02 check_mysql_health
-rwxr-xr-x 1 root   nagios 180947 Jun 23 10:35 check_mysql_query
-rwxr-xr-x 1 root   nagios 164403 Jun 23 10:35 check_nagios
-rwxrwxr-x 1 apache nagios  14602 May 31 19:03 check_nagioslogserver.php
-rwxrwxr-x 1 apache nagios   7381 May 31 19:03 check_nagios_performance.php
-rwxrwxr-x 1 apache nagios  20601 May 31 19:03 check_nagiosxiserver.php
-rwxrwxr-x 1 apache nagios  10065 May 31 19:03 check_ncpa.py
-rwxrwxr-x 1 apache nagios  10037 May 31 19:03 check_nna.py
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_nntp -> check_tcp
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_nntps -> check_tcp
-rwxrwxr-x 1 nagios nagios 132516 Jun 28 08:43 check_nrpe
-rwxr-xr-x 1 root   nagios 186283 Jun 23 10:35 check_nt
-rwxr-xr-x 1 root   nagios 187203 Jun 23 10:35 check_ntp
-rwxr-xr-x 1 root   nagios 183969 Jun 20 14:09 check_ntp_old
-rwxr-xr-x 1 root   nagios 178960 Jun 23 10:35 check_ntp_peer
-rwxr-xr-x 1 root   nagios 174933 Jun 23 10:35 check_ntp_time
-rwxr-xr-x 1 root   nagios 215864 Jun 23 10:35 check_nwstat
-rwxr-xr-x 1 root   nagios   9457 Jun 23 10:35 check_oracle
-rwxr-xr-x 1 root   nagios 165246 Jun 23 10:35 check_overcr
-rwxr-xr-x 1 root   nagios 188671 Jun 23 10:35 check_ping
-rwxrwxr-x 1 apache nagios   6183 May 31 19:02 check_pnp_rrds.pl
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_pop -> check_tcp
-rwxrwxr-x 1 apache nagios 388326 May 31 19:03 check_postgres.pl
-rwxr-xr-x 1 root   nagios 195086 Jun 23 10:35 check_procs
-rwxrwxr-x 1 apache nagios  29938 May 31 19:03 check_radius_adv
-rwxr-xr-x 1 apache apache   3740 Jun 26 12:20 check_radius.pl
-rwxr-xr-x 1 root   nagios 161424 Jun 23 10:35 check_real
-rwxr-xr-x 1 root   nagios   9679 Jun 23 10:35 check_rpc
-rwxrwxr-x 1 apache nagios   9743 May 31 19:02 check_rrdtraf
-rwxrwxr-x 1 apache nagios   5299 May 31 19:02 check_rrdtraf.php
-rwxr-xr-x 1 root   nagios   1533 Jun 23 10:35 check_sensors
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_simap -> check_tcp
-rwxrwxr-- 1 apache nagios   7599 May 31 19:02 check_sip
-rwxr-xr-x 1 root   nagios 243731 Jun 23 10:35 check_smtp
-rwxrwxr-x 1 apache nagios  20226 May 31 19:03 check_smtp_send
-rwxrwxr-x 1 apache nagios  10440 May 31 19:03 check_smtp_send_epn
-rwxr-xr-x 1 root   nagios 261104 Jun 23 10:35 check_snmp
-rwxrwxr-x 1 apache nagios  10983 May 31 19:02 check_snmp_boostedge.pl
-rwxrwxr-x 1 apache nagios  17866 May 31 19:02 check_snmp_cpfw.pl
-rwxrwxr-x 1 apache nagios   8763 May 31 19:02 check_snmp_css_main.pl
-rwxrwxr-x 1 apache nagios  16834 May 31 19:02 check_snmp_css.pl
-rwxrwxr-x 1 apache nagios  33722 May 31 19:02 check_snmp_env.pl
-rwxrwxr-x 1 apache nagios  23464 May 31 19:03 check_snmp_generic.pl
-rwxrwxr-x 1 apache nagios  31919 May 31 19:02 check_snmp_int.pl
-rwxrwxr-x 1 apache nagios  10140 May 31 19:02 check_snmp_linkproof_nhr.pl
-rwxrwxr-x 1 apache nagios  22931 May 31 19:03 check_snmp_load.pl
-rwxrwxr-x 1 apache nagios  23980 May 31 19:03 check_snmp_load_wizard.pl
-rwxrwxr-x 1 apache nagios  18782 May 31 19:02 check_snmp_mem.pl
-rwxrwxr-x 1 apache nagios  11930 May 31 19:02 check_snmp_nsbox.pl
-rwxrwxr-x 1 apache nagios  26296 May 31 19:03 check_snmp_process.pl
-rwxrwxr-x 1 apache nagios  26297 May 31 19:03 check_snmp_process_wizard.pl
-rwxrwxr-x 1 apache nagios  25538 May 31 19:03 check_snmp_storage.pl
-rwxrwxr-x 1 apache nagios  25539 May 31 19:03 check_snmp_storage_wizard.pl
-rwxrwxr-x 1 apache nagios  14521 May 31 19:02 check_snmp_vrrp.pl
-rwxrwxr-x 1 apache nagios  13120 May 31 19:03 check_snmp_win.pl
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_spop -> check_tcp
-rwxr-xr-x 1 root   nagios 161520 Jun 23 10:35 check_ssh
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_ssmtp -> check_tcp
-rwxr-xr-x 1 root   nagios 146550 Jun 23 10:35 check_swap
-rwxr-xr-x 1 root   nagios 221385 Jun 23 10:35 check_tcp
-rwxrwxr-x 1 apache nagios  22094 May 31 19:03 check_tftp.sh
-rwxr-xr-x 1 root   nagios 161654 Jun 23 10:35 check_time
lrwxrwxrwx 1 root   nagios      9 Jun 23 10:35 check_udp -> check_tcp
-rwxr-xr-x 1 root   nagios 173326 Jun 23 10:35 check_ups
-rwxr-xr-x 1 root   nagios 142668 Jun 23 10:35 check_uptime
-rwxr-xr-x 1 root   nagios 139687 Jun 23 10:35 check_users
-rwxr-xr-x 1 root   nagios   3032 Jun 23 10:35 check_wave
-rwxrwxr-x 1 apache nagios    307 May 31 19:02 check_webinject.sh
-rwxrwxr-x 1 apache nagios   7065 May 31 19:03 check_win_snmp_disk.pl
-rwxrwxr-x 1 apache nagios   5885 May 31 19:03 check_wmi_plus.conf
-rwxrwxr-x 1 apache nagios  66087 May 31 19:03 check_wmi_plus.ini
-rwxrwxr-x 1 apache nagios 335380 May 31 19:03 check_wmi_plus.pl
-rwxrwxr-x 1 apache nagios  18185 May 31 19:03 check_xisla.php
-rwxrwxr-x 1 apache nagios  40695 May 31 19:03 folder_watch.pl
-rwxr-xr-x 1 root   nagios 135768 Jun 23 10:35 negate
-rwxrwxr-x 1 apache nagios  42803 May 31 19:02 process_perfdata.pl
-rwxrwxr-x 1 apache nagios  66312 May 31 19:02 send_nsca
-rw-r--r-- 1 root   nagios  16956 Jun 28 09:02 tmp_xi_vars.cfg
-rwxr-xr-x 1 root   nagios 130687 Jun 23 10:35 urlize
-rwxr-xr-x 1 root   nagios   1914 Jun 23 10:35 utils.pm
-rwxr-xr-x 1 root   nagios   2791 Jun 23 10:35 utils.sh
