### ISSUE TITLE
NRPE 3.2.0 not available on SourceForge

### ISSUE THREAD

**Issue by sebastic** [NagiosEnterprises/nrpe#142]
Previous NRPE releases were (also) published on SourceForge under the Nagios project:

 https://sourceforge.net/projects/nagios/files/

The 3.2.0 is not available there, is that an oversight or should distributions now fetch the NRPE release tarballs from GitHub?

**Comment by hedenface** [comment]
This is not an oversight. Those with credentials to SourceForge have been on vacation. It should be taken care of sometime later today, actually.

**Comment by hedenface** [comment]
NRPE has been made available on source forge
