### ISSUE TITLE
seteuid(0): Operation not permitted

### ISSUE THREAD

**Issue by Fressikus** [NagiosEnterprises/nrpe#145]
After upgrading to Debian 9 and compiling NRPE 3.2.0, everything seems to be up and running. However, I'm getting the following line in /var/log/daemon.log every time the Nagios Core is making a connection:

Jul  5 17:02:58 hostname nrpe[8033]: ERROR: my_system() seteuid(0): Operation not permitted

This could very well be a simple misconfiguration on my part, I'm not sure. Any idea where this might come from?

**Comment by rhazdon** [comment]
I have got the same issue. Just upgraded nrpe to 3.2.0 on Debian 9.

**Comment by hedenface** [comment]
See issue #140 @rhazdon and @Fressikus This was resolved in maint commit: https://github.com/NagiosEnterprises/nrpe/commit/005e20ffec489bb56871911463d41ca5a465583d

It will be released in 3.2.1

**Comment by rhazdon** [comment]
Thank you very much, @hedenface! :)
