### ISSUE TITLE
NRPE 3.2.0 ERROR: my_system() seteuid(0): Operation not permitted

### ISSUE THREAD

**Issue by johnbritto1** [NagiosEnterprises/nrpe#147]
I have compiled check_nrpe plugin 3.2.0 only on Nagios Server and Nagios_Plugin 2.2.1 on the Nagios Client [Ubuntu 16.04] using [link](https://support.nagios.com/kb/article.php?id=515#CentOS)
I checked the NRPE handshake successfully and plugins return output but on the client Syslog, I get 

ERROR: my_system() seteuid(0): Operation not permitted

On NRPE Daemon restart via systemd :

Jul  6 04:20:20 odoo nrpe[17029]: ERROR: my_system() seteuid(0): Operation not permitted
Jul  6 04:20:43 odoo nrpe[3841]: Caught SIGTERM - shutting down...
Jul  6 04:20:43 odoo systemd[1]: Stopping Nagios Remote Plugin Executor...
Jul  6 04:20:43 odoo nrpe[3841]: **ERROR: remove_pid_file() seteuid(0): Operation not permitted**
Jul  6 04:20:43 odoo nrpe[3841]: Daemon shutdown
Jul  6 04:20:43 odoo systemd[1]: Stopped Nagios Remote Plugin Executor.
Jul  6 04:20:43 odoo systemd[1]: Started Nagios Remote Plugin Executor.
Jul  6 04:20:43 odoo nrpe[17204]: Starting up daemon
Jul  6 04:20:43 odoo nrpe[17204]: Server listening on 0.0.0.0 port 5666.
Jul  6 04:20:43 odoo nrpe[17204]: Server listening on :: port 5666.

Please assist.

**Comment by hedenface** [comment]
This was fixed in commit https://github.com/NagiosEnterprises/nrpe/commit/005e20ffec489bb56871911463d41ca5a465583d in the maint branch. Will be released in 3.2.1. See issues: #145, #140, #139.
