### ISSUE TITLE
ERROR: my_system() seteuid(0): Operation not permitted

### ISSUE THREAD

**Issue by jsteel44** [NagiosEnterprises/nrpe#148]
Since updating from 3.1.1 to 3.2.0 my log is flooded with:

`ERROR: my_system() seteuid(0): Operation not permitted`

NRPE seems to work OK, but what is the meaning of this error and why has it appeared with 3.2.0? Reverting back to 3.1.1 stops the errors from occurring. Thanks

**Comment by hedenface** [comment]
This was fixed in https://github.com/NagiosEnterprises/nrpe/commit/005e20ffec489bb56871911463d41ca5a465583d and will be included in 3.2.1
