### ISSUE TITLE
Connection Timeout and Connection Refused messages need a new line

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nrpe#15]
When I run check_nrpe against a host where it isn't allowed or doesn't hear back from it, there needs to be a new line added at the end.

Example 1:
<pre>[root@xitest libexec]# ./check_nrpe -H ub01
connect to address 10.25.13.5 port 5666: Connection refused
connect to host ub01 port 5666: Connection refused[root@xitest libexec]# </pre>

Example 2:
<pre>[root@xitest libexec]# ./check_nrpe -H win2008r2-01
connect to address 10.25.14.2 port 5666: No route to host
connect to host win2008r2-01 port 5666: No route to host[root@xitest libexec]# </pre>

Here is an example where the host is not allowed but adds the correct new line:
<pre>[root@xitest libexec]# ./check_nrpe -H W8DEV
CHECK_NRPE: Received 0 bytes from daemon.  Check the remote server logs for error messages.
[root@xitest libexec]# </pre>

**Comment by jfrickson** [comment]
Merged @awiddersheim pull request into https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC2
