### ISSUE TITLE
"Warning: Could not set effective GID=" messages

### ISSUE THREAD

**Issue by xalasys-luc** [NagiosEnterprises/nrpe#157]
Log contains numerous "Warning: Could not set effective GID=" messages when npre is started from inetd.

Probleem seems to originate from the call to drop_privileges() in

    run_inetd() --> handle_connection() --> my_system() --> drop_privileges()

**Comment by xalasys-luc** [comment]
FYI -- On my servers, I (temporarily) fixed it like this for nrpe-3.1.1:

    diff nrpe.c nrpe.c-patched 
    2165c2165,2167
    <               drop_privileges(nrpe_user, nrpe_group, 1);      /* drop privileges */
    ---
    >               if ( use_inetd == FALSE ) {
    >                       drop_privileges(nrpe_user, nrpe_group, 1);      /* drop privileges */
    >               }

**Comment by hedenface** [comment]
I put the fix inside of `drop_privileges()` so that it always skips during inetd operation. Fix is here: https://github.com/NagiosEnterprises/nrpe/commit/aa0d1e05da4ae592f2738d44fe2f721c5c20988a
