### ISSUE TITLE
check_nrpe  arguments (-a) error with director

### ISSUE THREAD

**Issue by lamaratonaug** [NagiosEnterprises/nrpe#161]
Hello

i have one problem witch icinga2 + director

by command line : 

./check_nrpe -H 192.168.1.245 -c check_eventlog -t 50 -a "file=system" "filter=written > -1m" "detail-syntax=%(level): %(source): %(id): %(message)" truncate=200

OK: Event log seems fine|'problem_count'=0;0;0

by director : 

Plugin Output
Incorrect command line arguments supplied

any ideas ?

I have configured the arguments -a like data source array

**Comment by box293** [comment]
Try using single quotes

**Comment by hedenface** [comment]
Check the icinga forums for help with their director.
