### ISSUE TITLE
Read from mysql generated garbled

### ISSUE THREAD

**Issue by ArmorHerO** [NagiosEnterprises/nrpe#167]
I wrote a plugin, read the Chinese characters from the mysql database, but read the results are '??????' my version is 3.1.1 I try to upgrade him to 3.2.1, or will happen the same Problem, but I dropped it to 2.1.2 when the problem is gone, this is the version of the problem or I use the problem?

**Comment by hedenface** [comment]
Back up a teensy bit, please.

Your version of **what** is 3.1.1? What are you upgrading to 3.2.1? And let's see your plugin.

**Comment by ArmorHerO** [comment]
sorry.... my server is centos7.2 my nrpe version is 3.1.1  ,I installed nrpe 3.2.1 from another server
I have a script in the sql statement as follows, it is implemented in the shell and through the implementation of the results of nrpe not the same

mysql -N  -e" SELECT mac_attr FROM devbox.Anloq_equipments WHERE (eqp_name NOT LIKE'呵呵%' AND eqp_name NOT LIKE '哈哈%') AND is_deleted=0
"

**Comment by ArmorHerO** [comment]
like this 
<img width="767" alt="2017-09-20 8 48 10" src="https://user-images.githubusercontent.com/18901031/30644507-28865e12-9e45-11e7-82cb-d31a4a882aab.png">

**Comment by ArmorHerO** [comment]
like this   <img width="767" alt="2017-09-20 8 48 10" src="https://user-images.githubusercontent.com/18901031/30644543-42afa118-9e45-11e7-9d6e-47796fc95559.png">

**Comment by jomann09** [comment]
You may have to set your charset to utf-8 when you connect to mysql, how are you connecting to it?

**Comment by ArmorHerO** [comment]
Ok i solved this problem and I added it in the configuration file
[client]
default-character-set = utf8

[mysql]
default-character-set = utf8

thank you very much！
sorry for my stupid

**Comment by jomann09** [comment]
Awesome, glad that solved your issue. Feel free to make another if you have any other problems.
