### ISSUE TITLE
nrpe children (or grandchildren?) hanging and never finishing

### ISSUE THREAD

**Issue by hkowallik** [NagiosEnterprises/nrpe#169]
Environment is RHEL7 running on VMware infrastructure.

Since upgrading to version 3.1.1 (offilcial Redhat RPM) I have nrpe child or grandchild procceses piling up on some virtual machines:

    nagios    17390      1  0 10:30 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios    41897      1  0 10:53 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios    48047      1  0 10:59 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios    56905      1  0 11:07 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios    64263      1  0 11:14 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios    69645      1  0 11:19 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios    75942      1  0 09:24 ?        00:00:02 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios    89393      1  0 11:37 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios   105588      1  0 11:52 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios   121378      1  0 10:06 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios   123057      1  0 10:08 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios   124421      1  0 10:09 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
    nagios   127745      1  0 10:12 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d

This happens only (or mainly?) on busy machines which have some long running checks.
According to strace/lsof the process hangs on a read on the socket to the nagios server:

    strace -p 121378
    strace: Process 121378 attached
    read(8, 

    nrpe    121378 nagios    8u  IPv4            2133170      0t0     TCP problemhost:5666->nagios-host:38828 (ESTABLISHED)

This port is no longer present on nagios-host.

When I switch on debugging the log entries for that child end with

     Host address is in allowed_hosts
and it never reaches the point of

     Host nagios-host is asking for command abc to be run

The problem goes away if I go back to version 2.15
The problem does not go away if I change to non-forking mode

**Comment by hkowallik** [comment]
UPDATE:
On the nagios host which issues the check_nrpe command I see SSL errors
    Error: Could not complete SSL handshake with problemhost: rc=-1 SSL-error=5

For many (not all) hanging processes I get such a message on the nagios-host at the time the hanging process was forked.

**Comment by hedenface** [comment]
You say the problem goes away if you go back to version 2.15. What happens if you use a newer version than 3.1.1?

**Comment by lvasiliev** [comment]
Hello, we use FreeBSD 11.1 amd64 and nrpe-3.2.1. Not so long ago, we recorded an increased CPU load on a group of their servers which there were packet losses. 

top out (for example, pid from truss is different):

 PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
11238 root          1  76    0 17520K  5196K CPU0    0   0:02 104.01% nrpe3
 7985 root          1 103    0 17520K  5192K CPU9    9  42:07 101.44% nrpe3
 8590 root          1 103    0 17520K  5196K CPU4    4  35:46 101.44% nrpe3
10999 root          1 103    0 17520K  5196K CPU7    7   3:23 101.44% nrpe3

Package version:

srv2# pkg info nrpe3
nrpe3-3.2.1
Name           : nrpe3
Version        : 3.2.1
Installed on   : Tue Feb 13 14:31:17 2018 MSK
Origin         : net-mgmt/nrpe3
Architecture   : FreeBSD:11:amd64
Prefix         : /usr/local
Categories     : net-mgmt
Licenses       : GPLv2
Maintainer     : zeising@FreeBSD.org
WWW            : http://www.nagios.org/
Comment        : Nagios Remote Plugin Executor
Options        :
        ARGS           : off
        MONPLUGINS     : off
        NAGPLUGINS     : on
        SSL            : on

truss log:

 1021: select(5,{ 4 },0x0,0x0,0x0)               = 1 (0x1)
 1021: accept(4,{ AF_INET 91.103.XX.XX:26522 },0x7fffffffe3dc) = 5 (0x5)
 9237: <new process>
 1021: fork()                                    = 9237 (0x2415)
 1021: close(5)                                  = 0 (0x0)
 9238: <new process>
 9237: fork()                                    = 9238 (0x2416)
 9238: sigaction(SIGQUIT,{ 0x407f50 SA_RESTART|SA_NODEFER ss_t },0x0) = 0 (0x0)
 9238: sigaction(SIGTERM,{ 0x407f50 SA_RESTART|SA_NODEFER ss_t },0x0) = 0 (0x0)
 9237: sigprocmask(SIG_BLOCK,{ SIGHUP|SIGINT|SIGQUIT|SIGKILL|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|
 1021: select(5,{ 4 },0x0,0x0,0x0)               = 1 (0x1)
 1021: accept(4,{ AF_INET 91.103.XX.XX:26522 },0x7fffffffe3dc) = 5 (0x5)
 9237: <new process>
 1021: fork()                                    = 9237 (0x2415)
 1021: close(5)                                  = 0 (0x0)
 9238: <new process>
 9237: fork()                                    = 9238 (0x2416)
 9238: sigaction(SIGQUIT,{ 0x407f50 SA_RESTART|SA_NODEFER ss_t },0x0) = 0 (0x0)
 9238: sigaction(SIGTERM,{ 0x407f50 SA_RESTART|SA_NODEFER ss_t },0x0) = 0 (0x0)
 9237: sigprocmask(SIG_BLOCK,{ SIGHUP|SIGINT|SIGQUIT|SIGKILL|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|
SIGINFO|SIGUSR1|SIGUSR2 },{ }) = 0 (0x0)
 9238: sigaction(SIGHUP,{ 0x407f50 SA_RESTART|SA_NODEFER ss_t },0x0) = 0 (0x0)
 9238: close(4)                                  = 0 (0x0)
 9237: sigprocmask(SIG_SETMASK,{ },0x0)          = 0 (0x0)
 9237: sigprocmask(SIG_BLOCK,{ SIGHUP|SIGINT|SIGQUIT|SIGKILL|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|
SIGINFO|SIGUSR1|SIGUSR2 },{ }) = 0 (0x0)
 9238: getpeername(5,{ AF_INET 91.103.XX.XX:26522 },0x7fffffffdf6c) = 0 (0x0)
 9237: sigprocmask(SIG_SETMASK,{ },0x0)          = 0 (0x0)
 9238: getpid()                                  = 9238 (0x2416)
 9237: sigprocmask(SIG_BLOCK,{ SIGHUP|SIGINT|SIGQUIT|SIGKILL|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2 },{ }) = 0 (0x0)
 9238: getpeername(5,{ AF_INET 91.103.XX.XX:26522 },0x7fffffffdb1c) = 0 (0x0)
 9237: sigprocmask(SIG_SETMASK,{ },0x0)          = 0 (0x0)
 9238: getsockname(5,{ AF_INET 80.239.174.50:5666 },0x7fffffffdb1c) = 0 (0x0)
 9237: sigprocmask(SIG_BLOCK,{ SIGHUP|SIGINT|SIGQUIT|SIGKILL|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2 },{ }) = 0 (0x0)
 9238: sigprocmask(SIG_BLOCK,0x0,{ })            = 0 (0x0)
 9237: sigprocmask(SIG_SETMASK,{ },0x0)          = 0 (0x0)
 9238: open("/etc/hosts.allow",O_RDONLY,0666)    = 4 (0x4)
 9238: fstat(4,{ mode=-rw-r--r-- ,inode=963534,size=3459,blksize=32768 }) = 0 (0x0)
 9237: sigprocmask(SIG_BLOCK,{ SIGHUP|SIGINT|SIGQUIT|SIGKILL|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2 },{ }) = 0 (0x0)
 9237: sigprocmask(SIG_SETMASK,{ },0x0)          = 0 (0x0)
 9238: read(4,"#\n# hosts.allow access control "...,32768) = 3459 (0xd83)
 9237: sigprocmask(SIG_BLOCK,{ SIGHUP|SIGINT|SIGQUIT|SIGKILL|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2 },{ }) = 0 (0x0)
 9237: sigprocmask(SIG_SETMASK,{ },0x0)          = 0 (0x0)
 9238: close(4)                                  = 0 (0x0)
 9238: sigprocmask(SIG_SETMASK,{ },0x0)          = 0 (0x0)
 9237: exit(0x0)                                
 9237: process exit, rval = 0
 1021: wait4(9237,0x0,0x0,0x0)                   = 9237 (0x2415)
 9238: read(5,0x801aa8180,11)                    ERR#35 'Resource temporarily unavailable'
 9238: read(5,0x801aa8180,11)                    ERR#35 'Resource temporarily unavailable'
 9238: read(5,0x801aa8180,11)                    ERR#35 'Resource temporarily unavailable'
 9238: read(5,0x801aa8180,11)                    ERR#35 'Resource temporarily unavailable'
 9238: read(5,0x801aa8180,11)                    ERR#35 'Resource temporarily unavailable'
 9238: read(5,0x801aa8180,11)                    ERR#35 'Resource temporarily unavailable'
 9238: read(5,0x801aa8180,11)                    ERR#35 'Resource temporarily unavailable'
...cycle....

We emulate this situation with ipfw firewall (70% packet loss from our monitoring server):
00150    3918   1237188 prob 0.700000 deny ip from 91.103.XX.XX to me

**Comment by lvasiliev** [comment]
We compiled nrpe3 with debugging information and found the place in which the loop occurs. And I don't understand why in /var/log/all.log nrpe3 logging port is 1128. Sockstat out another value, in this case 26628. 

```
CPU: 72.1% user,  0.0% nice, 27.9% system,  0.0% interrupt,  0.0% idle
Mem: 584M Active, 4493M Inact, 1954M Wired, 1243M Buf, 16G Free
ARC: 90M Total, 52M MFU, 38M MRU, 56K Anon, 216K Header, 306K Other
     19M Compressed, 77M Uncompressed, 4.03:1 Ratio
Swap: 4096M Total, 4096M Free

  PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
 2452 nagios        1  87    0 17532K  5596K RUN     4   1:06  60.25% nrpe3
 2470 nagios        1  87    0 17532K  5632K RUN     6   0:50  59.49% nrpe3
 2560 nagios        1  85    0 17532K  5596K CPU8    8   0:09  56.91% nrpe3
 2252 nagios        1  87    0 17532K  5624K CPU0    0   1:38  54.66% nrpe3
 2466 nagios        1  87    0 17532K  5624K RUN     2   0:55  49.29% nrpe3
 2276 nagios        1  87    0 17532K  5596K RUN     2   1:52  47.04% nrpe3
 2498 nagios        1  87    0 17532K  5596K RUN     0   0:32  46.14% nrpe3
 1923 nagios        1  86    0 17532K  5596K RUN     8   5:47  42.98% nrpe3
 2517 nagios        1  87    0 17532K  5596K CPU4    4   0:31  40.78% nrpe3
 2551 nagios        1  87    0 17532K  5596K CPU6    6   0:23  40.13% nrpe3
 2164 nagios        1  84    0 17532K  5596K RUN     9   3:12  38.49% nrpe3
 2330 nagios        1  86    0 17532K  5596K RUN    10   1:21  38.46% nrpe3
 2155 nagios        1  82    0 17532K  5596K RUN     1   2:49  33.97% nrpe3
 2496 nagios        1  82    0 17532K  5596K CPU11  11   0:28  33.68% nrpe3
 2468 nagios        1  82    0 17532K  5596K RUN    11   0:41  33.68% nrpe3
 2519 nagios        1  82    0 17532K  5596K CPU3    3   0:18  33.68% nrpe3
 2272 nagios        1  82    0 17532K  5596K RUN     7   2:06  33.68% nrpe3
 2166 nagios        1  82    0 17532K  5624K RUN     5   2:21  33.68% nrpe3
 2521 nagios        1  82    0 17532K  5596K RUN     7   0:17  33.68% nrpe3
 2133 nagios        1  82    0 17532K  5616K RUN     5   2:38  33.68% nrpe3
 2555 nagios        1  81    0 17532K  5608K RUN     1   0:10  33.67% nrpe3
 2168 nagios        1  82    0 17532K  5596K RUN    11   2:21  33.67% nrpe3
 2416 nagios        1  82    0 17532K  5596K CPU7    7   0:57  33.67% nrpe3
 2584 nagios        1  77    0 17532K  5632K RUN     9   0:03  33.67% nrpe3
 2474 nagios        1  82    0 17532K  5596K CPU1    1   0:42  33.39% nrpe3
 2476 nagios        1  82    0 17532K  5624K RUN     3   0:37  33.08% nrpe3
 2454 nagios        1  86    0 17532K  5596K CPU10  10   0:58  33.01% nrpe3
 2173 nagios        1  82    0 17532K  5624K RUN     3   2:35  29.45% nrpe3
 2480 nagios        1  82    0 17532K  5596K CPU5    5   0:30  28.87% nrpe3
 2337 nagios        1  84    0 17532K  5596K CPU9    9   1:12  28.86% nrpe3

srv2# ps uwwww -p 1923
USER    PID %CPU %MEM   VSZ  RSS TT  STAT STARTED    TIME COMMAND
nagios 1923 95.2  0.0 17532 5596  -  R    11:03   6:38.31 /home/admin/nrpe/nrpe3 -c /usr/local/etc/nrpe.cfg -d

srv2# grep 1923 /var/log/all.log
Jun  9 11:03:13 srv2 nrpe[1923]: Connection from 91.103.XX.XX port 1128

srv2# fstat -p 1923
USER     CMD          PID   FD MOUNT      INUM MODE         SZ|DV R/W
nagios   nrpe3       1923 text /        1204114 -rwxr-xr-x  175428  r
nagios   nrpe3       1923   wd /             2 drwxr-xr-x    1024  r
nagios   nrpe3       1923 root /             2 drwxr-xr-x    1024  r
nagios   nrpe3       1923    0 /dev         24 crw-rw-rw-    null  r
nagios   nrpe3       1923    1 /dev         24 crw-rw-rw-    null  w
nagios   nrpe3       1923    2 /dev         24 crw-rw-rw-    null  w
nagios   nrpe3       1923    3* local dgram fffff8004a523780 <-> fffff8004a7955a0
nagios   nrpe3       1923    5* internet stream tcp fffff8004ad11410

srv2# sockstat -s | grep 1923
nagios   nrpe3      1923  3  dgram  -> /var/run/log
nagios   nrpe3      1923  5  tcp4   80.239.XX.XX:5666    91.103.XX.XX:26628   ESTABLISHED

srv2# lldb -p 1923
(lldb) process attach --pid 1923
Process 1923 stopped

Executable module set to "/home/admin/nrpe/nrpe3".
Architecture set to: x86_64--freebsd11.1.
(lldb) bt
* thread #1
  * frame #0: 0x0000000800d19900 libcrypto.so.8`lh_retrieve + 64
    frame #1: 0x0000000800d27fb1 libcrypto.so.8`___lldb_unnamed_symbol529$$libcrypto.so.8 + 193
    frame #2: 0x0000000800d26439 libcrypto.so.8`ERR_get_state + 169
    frame #3: 0x0000000800d2662c libcrypto.so.8`ERR_clear_error + 12
    frame #4: 0x00000008008718c3 libssl.so.8`ssl23_accept + 67
    frame #5: nrpe3`handle_conn_ssl(sock=5, ssl_ptr=0x0000000801aa0700) at nrpe.c:1922
    frame #6: nrpe3`handle_connection(sock=5) at nrpe.c:1668
    frame #7: nrpe3`wait_for_connections at nrpe.c:1363
    frame #8: nrpe3`run_daemon at nrpe.c:647
    frame #9: nrpe3`main(argc=4, argv=0x00007fffffffeaf8) at nrpe.c:225
    frame #10: 0x0000000000403eaf nrpe3`_start + 383
(lldb) frame s 5
frame #5: nrpe3`handle_conn_ssl(sock=5, ssl_ptr=0x0000000801aa0700) at nrpe.c:1922
   1919         SSL_set_fd(ssl, sock);
   1920
   1921         /* keep attempting the request if needed */
-> 1922         while (((rc = SSL_accept(ssl)) != 1)
   1923                         && (SSL_get_error(ssl, rc) == SSL_ERROR_WANT_READ));
   1924
   1925         if (rc != 1) {
(lldb) frame info
frame #5: nrpe3`handle_conn_ssl(sock=5, ssl_ptr=0x0000000801aa0700) at nrpe.c:1922
(lldb) frame variable
(int) sock = 5
(void *) ssl_ptr = 0x0000000801aa0700
(const SSL_CIPHER *) c = 0x00007fffffffeaf0
(const char *) errmsg = 0x0000000000000000
(char [2048]) buffer = ""
(SSL *) ssl = 0x0000000801aa0700
(X509 *) peer = 0x0000000000000000
(int) rc = -1
(int) x = 0
(lldb)
```

**Comment by lvasiliev** [comment]
Approximate patch that solves this problem.
[nrpe3.patch.txt](https://github.com/NagiosEnterprises/nrpe/files/2124313/nrpe3.patch.txt)

**Comment by lvasiliev** [comment]
Hello, this issue is still relevant...

**Comment by avkarenow** [comment]
Hi,

FreeBSD 11.3, nrpe3-3.2.1 -- the same problem here.

CPU: 102.07% /usr/local/sbin/nrpe3 -c /usr/local/etc/nrpe.cfg -d
truss output:
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'
read(6,0x801b05a03,5)				 ERR#35 'Resource temporarily unavailable'

**Comment by lvasiliev** [comment]
https://github.com/NagiosEnterprises/nrpe/pull/207/commits/5f526d1f9d16c20bc987824fd8f1de7f40f6fad5
