### ISSUE TITLE
Problems with NRPE and debian 9

### ISSUE THREAD

**Issue by ibizista** [NagiosEnterprises/nrpe#181]
Hello,

We have a problem. When we try to execute a check over NRPE from our central server ( Version: 2.15 ) to a client with debian 9 ( Version: 3.0.1 ), depending of the script, maybe the executable don't work fine.
For example, the script check_mysql_health (https://labs.consol.de/nagios/check_mysql_health) fails with the next error.

`Can't connect to local MySQL server through socket '/tmp/mysql.sock'`

If I execute locally (ssh console) with the user nagios, the plugin works fine.

If I make a simple bash script with a basic command like

```
ls /home > /tmp/list.txt
echo "OK"
exit 0
```

The file list.txt don't be created

But if We run the daemon and the check with option -n all works!!
Other plugins like _check_procs_ works fine with and without -n

Any idea about what is the problem?

Thanks a lot

**Comment by box293** [comment]
Most likely you'll need to update your central server using 2.15 as it is using SSL methods that have been depreciated. The `-n` argument is stopping SSL from being used hence everything works.

We have a series of troubleshooting articles here: https://support.nagios.com/kb/category.php?id=93

**Comment by ibizista** [comment]
Thanks box293

I've compiled the last version (3.2.1) of NRPE plugin in the central server.
The problem persist. Same response from mysql check

`CRITICAL - cannot connect to information_schema. Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2 "No such file or directory")`

If I use -n parameter, the plugin can't connect

` CHECK_NRPE: Error - Could not connect to X.X.X.X: Connection reset by peer`

**Comment by ibizista** [comment]
I've find the real problem,but not the solution.
When I run the check nrpe from the central to the client, if the daemon in the client started from inetd, the check, fails.
If I run the daemon manually, but exactly like inetd, 

` /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -f`

The check works

This is the line in inet.d script

` start_daemon -p $PIDDIR/nrpe.pid $NICENESS $DAEMON  -c $CONFIG -d $NRPE_OPTS`

I've try to change -d by --inetd, but the result is the same

thanks

**Comment by ericloyd** [comment]
What does /etc/inetd.conf look like?  I'm guessing your system is not allowing remote connections via inetd.

**Comment by ibizista** [comment]
Thank you guys

```
cat /etc/services | grep 5666
nrpe		5666/tcp			# Nagios Remote Plugin Executor
```
```
netstat -an | grep tcp |grep 5666
tcp        0      0 0.0.0.0:5666            0.0.0.0:*               LISTEN     
tcp6       0      0 :::5666                 :::*                    LISTEN     
```
I think that the problem isn't the connection. I can run some nrpe check, but not all.
The script in /etc/inet.d/ are not working like a inet.d script. When I use it, this is the log

[ ok ] Restarting nagios-nrpe-server (via **systemctl**): nagios-nrpe-server.service

I've tried to recompile the daemon with systemd option

`./configure --enable-command-args --with-init-type=systemd`

This option create a script in 

` /lib/systemd/system/nrpe.service`

If I start the sevice, a ps show this

`nagios   20867     1  0 18:33 ?        00:00:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -f`

But some checks don't work. If I run the same line in the terminal, 

`/usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -f &`

Works like a charm

**Comment by hedenface** [comment]
What do the logs look like for checks that don't work?

**Comment by ibizista** [comment]
The log starting nrpe like a service

```
May 28 12:17:49 mvwordpress01 nrpe[57433]: Host address is in allowed_hosts
May 28 12:17:49 mvwordpress01 nrpe[57433]: Host X.X.X.X is asking for command 'check_mysql_general' to be run...
May 28 12:17:49 mvwordpress01 nrpe[57433]: Running command: /usr/lib/nagios/plugins/test.sh
May 28 12:17:49 mvwordpress01 nrpe[57434]: WARNING: my_system() seteuid(0): Operation not permitted
May 28 12:17:49 mvwordpress01 nrpe[57433]: Command completed with return code 0 and output: OK  test_text_2
May 28 12:17:49 mvwordpress01 nrpe[57433]: Return Code: 0, Output: OK  test_text_2
May 28 12:17:49 mvwordpress01 nrpe[57433]: Connection from X.X.X.X closed.

```


The log starting nrpe manually
```

May 28 12:24:53 mvwordpress01 nrpe[57664]: Host address is in allowed_hosts
May 28 12:24:53 mvwordpress01 nrpe[57664]: Host X.X.X.X is asking for command 'check_mysql_general' to be run...
May 28 12:24:53 mvwordpress01 nrpe[57664]: Running command: /usr/lib/nagios/plugins/test.sh
May 28 12:24:53 mvwordpress01 nrpe[57664]: Command completed with return code 0 and output: OK  /var/tmp/testfile.txt test_text_2
May 28 12:24:53 mvwordpress01 nrpe[57664]: Return Code: 0, Output: OK  /var/tmp/testfile.txt test_text_2
May 28 12:24:53 mvwordpress01 nrpe[57664]: Connection from X.X.X.X closed.
```
This is the difference

`May 28 12:17:49 mvwordpress01 nrpe[57434]: WARNING: my_system() seteuid(0): Operation not permitted`

The script that i'm using to test nrpe:

```
#!/bin/bash

PP=`/bin/ls -ltrh /var/tmp/testfile.txt |awk '{print $9}'`
PP2="test_text_2"

echo "OK " $PP $PP2

exit 0

```
I've try to use sudo in the nrpe.cfg 

`command[check_mysql_general]=sudo /usr/lib/nagios/plugins/test.sh`

But  nothing change.

In this moments I am using 3.2.1 version to the test.

**Comment by hedenface** [comment]
Does the plugin require root privileges? That is simply a warning indicating that it can't pretend to effectively be root. What does your systemd service file look like?

You can see the lines after the warning indicate that nrpe was able to run the plugin.

**Comment by ericloyd** [comment]
Please, what does /etc/inetd.conf look like?

**Comment by ibizista** [comment]
Eureka!!

Simply, I've changed the config of systemd to

PrivateTmp=false

Thanks!!

**Comment by box293** [comment]
Great, thanks for letting us know the solution. I'll be able to add that to the existing KB articles.
