### ISSUE TITLE
use a script to monitor docker swarm quorum via NRPE

### ISSUE THREAD

**Issue by sushantohalder** [NagiosEnterprises/nrpe#185]
NRPE is used allow Nagios to monitor local resources(like CPU load, memory usage, etc.). It uses scripts to monitor such resources based on the exit code of the script. So issue is to create a script that will monitor the swarm nodes and tells that when the swarm cluster is intact and when not. It should also give a warning if anyone of the manager is down.

**Comment by box293** [comment]
Have you checked out the Nagios Exchange for any Docker plugins that people have already written?

https://exchange.nagios.org/index.php?option=com_mtree&task=search&Itemid=74&searchword=docker

**Comment by sushantohalder** [comment]
So none of the given scripts could be used for monitoring docker swarm quorum. So I wrote one script to do the job. And tested it in the dev, stg and prod. 

This is the link to the script that I wrote.
https://github.com/sushantohalder/SwarmStatusCheck

@box293 How can I add this script to the link that you mentioned?

**Comment by box293** [comment]
If you go to https://exchange.nagios.org/#/ you can create your own user account (Login section on right hand pane). Once you have an account you can upload/link your plugin and it will be published.
