### ISSUE TITLE
Document keep_env_vars

### ISSUE THREAD

**Issue by tatref** [NagiosEnterprises/nrpe#187]
I'm trying to use a check that requires the `LD_LIBRARY_PATH` env variable to be set.

This was working on older nrpe version (2.7.1)

With the current version, the `clean_environ` function deletes those variables. However, it seems that the `keep_env_vars` config file flag should disable or alter this behaviour?

I tried setting `keep_env_vars` to:
* LD_LIBRARY_PATH 
* 0
* 1

None of theses are working

Could you give me some hint about this?
Thanks!

**Comment by hedenface** [comment]
After reading `clean_environ` it looks like no matter what `keep_env_vars` is set to it only sets the following environment variables:

```
PATH
IFS
LOGNAME
USER
HOME
SHELL
```

But if you have `LD_LIBRARY_PATH` already set in `/etc/environment` and you specify it in the `keep_env_vars` it should not unset (via `unsetenv()` call).
