### ISSUE TITLE
NRPE returns OK if check can't be executed

### ISSUE THREAD

**Issue by koenwtje** [NagiosEnterprises/nrpe#19]
When attempting to execute an empty file with the execute bit set using `sh -c`, sh returns 0 (even though the execve(2) call fails). Since NRPE executes the check plugins using `sh -c`, nagios will think everything is fine, while in reality nothing is checked.

I recently deployed a faulty build of one of our checks (with an empty file instead of the actual check), which we didn't immediately notice because nagios was still happy.

Is there any way around this? Would stuff break if NRPE were to execute the plugin directly, instead of using sh (so NRPE can check the execve return code itself)?

**Comment by awiddersheim** [comment]
I might be wrong but this change might also catch the problem you had:

https://github.com/NagiosEnterprises/nrpe/pull/14

**Comment by koenwtje** [comment]
Yes, I think you're right. NRPE did also show ""NRPE: Unable to read output", so considering no output as a issue would catch this issue as well.

**Comment by jfrickson** [comment]
Fixed with commit https://github.com/NagiosEnterprises/nrpe/commit/314749e366d0b817745060d6befe076cc15dbc39
in branch https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC2
