### ISSUE TITLE
Amazon Linux 2 Support

### ISSUE THREAD

**Issue by christrumid** [NagiosEnterprises/nrpe#203]
Currently installation on Amazon Linux 2 fails saying Amazon Linux is not supported.  It works find on Amazon Linux (first version).  We are going to upgrade but need monitoring to work before we do so.

**Comment by box293** [comment]
How are you installing it?

**Comment by christrumid** [comment]
root@ip-172-31-53-156 tmp]# cd /tmp ; wget https://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz ; tar xvfz linux-nrpe-agent.tar.gz ; cd linux-nrpe-agent ; ./fullinstall -n
--2018-11-15 13:29:00--  https://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz
Resolving assets.nagios.com (assets.nagios.com)... 72.14.181.71, 2600:3c00::f03c:91ff:fedf:b821
Connecting to assets.nagios.com (assets.nagios.com)|72.14.181.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3550625 (3.4M) [application/x-gzip]
Saving to: ‘linux-nrpe-agent.tar.gz.1’

100%[============================================================================================================================================================>] 3,550,625   1.42MB/s   in 2.4s   

2018-11-15 13:29:03 (1.42 MB/s) - ‘linux-nrpe-agent.tar.gz.1’ saved [3550625/3550625]

linux-nrpe-agent/
linux-nrpe-agent/0-repos
linux-nrpe-agent/1-prereqs
linux-nrpe-agent/2-usersgroups
linux-nrpe-agent/3-services
linux-nrpe-agent/4-firewall
linux-nrpe-agent/A-subcomponents
linux-nrpe-agent/CHANGES.txt
linux-nrpe-agent/fullinstall
linux-nrpe-agent/get-os-info
linux-nrpe-agent/init.sh
linux-nrpe-agent/nagios.firewallapps
linux-nrpe-agent/packages/
linux-nrpe-agent/packages/epel-release-5-4.noarch.rpm
linux-nrpe-agent/packages/epel-release-latest-6.noarch.rpm
linux-nrpe-agent/packages/epel-release-latest-7.noarch.rpm
linux-nrpe-agent/subcomponents/
linux-nrpe-agent/subcomponents/extraplugins/
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/.gitignore
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/.perlcriticrc
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/check_postgres.pl
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/check_postgres.pl.asc
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/check_postgres.pl.html
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/Makefile.PL
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/MANIFEST
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/MANIFEST.SKIP
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/META.yml
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/README
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/SIGNATURE
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/TODO
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/00_basic.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/00_signature.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/00_test_tester.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_autovac_freeze.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_backends.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_bloat.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_checkpoint.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_connection.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_custom_query.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_database_size.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_dbstats.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_disabled_triggers.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_disk_space.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_fsm_pages.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_fsm_relations.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_last_analyze.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_last_vacuum.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_listener.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_locks.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_logfile.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_new_version_cp.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_new_version_pg.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_prepared_txns.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_query_runtime.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_query_time.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_relation_size.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_replicate_row.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_same_schema.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_sequence.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_settings_checksum.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_timesync.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_txn_idle.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_txn_time.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_txn_wraparound.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_version.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/02_wal_files.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/03_translations.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/04_timeout.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/99_cleanup.t
linux-nrpe-agent/subcomponents/extraplugins/check_postgres-2.12.0/t/CP_Testing.pm
linux-nrpe-agent/subcomponents/extraplugins/check_rrdtraf-0.5/
linux-nrpe-agent/subcomponents/extraplugins/check_rrdtraf-0.5/Changes
linux-nrpe-agent/subcomponents/extraplugins/check_rrdtraf-0.5/check_rrdtraf
linux-nrpe-agent/subcomponents/extraplugins/check_rrdtraf-0.5/INSTALL
linux-nrpe-agent/subcomponents/extraplugins/check_rrdtraf-0.5/README
linux-nrpe-agent/subcomponents/extraplugins/install
linux-nrpe-agent/subcomponents/extraplugins/nagios-check_sip-1.2/
linux-nrpe-agent/subcomponents/extraplugins/nagios-check_sip-1.2/CHANGES
linux-nrpe-agent/subcomponents/extraplugins/nagios-check_sip-1.2/check_sip
linux-nrpe-agent/subcomponents/extraplugins/nagios-check_sip-1.2/COPYING
linux-nrpe-agent/subcomponents/extraplugins/nagios-check_sip-1.2/README
linux-nrpe-agent/subcomponents/extraplugins/nagios-snmp-plugins.1.1.1.tgz
linux-nrpe-agent/subcomponents/extraplugins/nagisk/
linux-nrpe-agent/subcomponents/extraplugins/nagisk-1.1.1.tgz
linux-nrpe-agent/subcomponents/extraplugins/nagisk/nagisk.pl
linux-nrpe-agent/subcomponents/extraplugins/nagisk/README
linux-nrpe-agent/subcomponents/extraplugins/NOTES
linux-nrpe-agent/subcomponents/extraplugins/plugins/
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_asterisk.pl
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_asterisk_sip_peers.sh
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_cpu_stats.sh
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_init_service
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_netstat.pl
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_open_files.pl
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_services
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_sip
linux-nrpe-agent/subcomponents/extraplugins/plugins/check_yum
linux-nrpe-agent/subcomponents/extraplugins/plugins/custom_check_mem
linux-nrpe-agent/subcomponents/extraplugins/plugins/custom_check_procs
linux-nrpe-agent/subcomponents/extraplugins/rrdtraf.tar.gz
linux-nrpe-agent/subcomponents/install
linux-nrpe-agent/subcomponents/nagiosplugins/
linux-nrpe-agent/subcomponents/nagiosplugins/install
linux-nrpe-agent/subcomponents/nagiosplugins/nagios-plugins-2.2.1.tar.gz
linux-nrpe-agent/subcomponents/nrpe/
linux-nrpe-agent/subcomponents/nrpe/install
linux-nrpe-agent/subcomponents/nrpe/mods/
linux-nrpe-agent/subcomponents/nrpe/mods/cfg/
linux-nrpe-agent/subcomponents/nrpe/mods/cfg/nrpe/
linux-nrpe-agent/subcomponents/nrpe/mods/cfg/nrpe.cfg
linux-nrpe-agent/subcomponents/nrpe/mods/cfg/nrpe/asterisk.cfg
linux-nrpe-agent/subcomponents/nrpe/mods/cfg/nrpe/common.cfg
linux-nrpe-agent/subcomponents/nrpe/nrpe-3.2.1.tar.gz
linux-nrpe-agent/subcomponents/nrpe/post-install
linux-nrpe-agent/xi-sys.cfg
linux-nrpe-agent/xivar
Amazon is not currently supported. Please use either Red Hat, CentOS, Oracle Linux, CloudLinux, SUSE Enterprise, OpenSUSE, Ubuntu, or Debian.

**Comment by box293** [comment]
OK great this is a custom build that is provided for Nagios XI, which they could update to support Amazon Linux 2.

However you should still be able to compile it from source on Amazon Linux using the RHEL instructions:
https://support.nagios.com/kb/article.php?id=515#RHEL

**Comment by d4lk0s** [comment]
The following has worked for me on Amazon Linux 2:

1. Add "Amazon" as an approved OS by editing the NRPE agent "fullinstall" file. For example, I added it to the CentOS/RedHat line like this:
`if [ "$distro" == "CentOS" ] || [ "$distro" == "RedHatEnterpriseServer" ] || [ "$distro" == "Amazon" ]; then`

2. Install the EPEL repo:
`yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`

3. Install the following packages:
`yum install -y gcc glibc glibc-common openssl openssl-devel perl wget patch xinetd`

4. Run the NRPE agent install script:
`./fullinstall`

That has worked for me on several Amazon Linux 2 instances.
