### ISSUE TITLE
nrpe incompatible with red hat 8

### ISSUE THREAD

**Issue by schlatter** [NagiosEnterprises/nrpe#208]
Hi Guys,
I'm currently testing with Red Hat 8.0. Unfortunately there is no Red Hat 8 EPEL right now, so I used the EPEL 7 and I encountered a bug with the nrpe-3.2.1-8.el7.x86_64 package. This seems to be regarding the deprecated tcp_wrapper https://fedoraproject.org/wiki/Changes/Deprecate_TCP_wrappers . This is the following error:

```
~# yum install nrpe
Updating Subscription Management repositories.
Last metadata expiration check: 1:58:28 ago on Mon May 13 10:20:12 2019.
Error: 
 Problem: conflicting requests
  - nothing provides libwrap.so.0()(64bit) needed by nrpe-3.2.1-8.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
Is this a know issue, is there an workaround available?
kind regards

**Comment by box293** [comment]
Until EPEL 8 is available you are going to need to build NRPE from source. I'll endeavour to give this a go and see if it works.

**Comment by schlatter** [comment]
Hi box293, thanks for the fast reply. I build it from source and now it's working in my testenvironment, for production use I'll wait for EPEL8.

**Comment by liberodark** [comment]
Compile not work on RHEL 8 in 3.2.1

**Comment by liberodark** [comment]
Yes is work when you build nrpe : https://github.com/liberodark/nrpe-installer
