### ISSUE TITLE
Translated the English documentation of the NRPE plugin into Chinese

### ISSUE THREAD

**Issue by fengtianya** [NagiosEnterprises/nrpe#210]
Hello, I translated the English documentation of the NRPE plugin into Chinese. Does anybody need a translated document? Is there any way to put it in the project? Who should I submit to, how do I submit the attachment?

**Comment by Madlohe** [comment]
The best place I know of would be the [Nagios Exchange](https://exchange.nagios.org), which is where most people put plugins/integrations/other documentation. As far as I know, that website gets more visibility than any individual repository on our Github.

**Comment by fengtianya** [comment]
Thank you for your suggestion, I will try to contact Nagios Exchange! @Madlohe

**Comment by Madlohe** [comment]
Sounds good! I'll close this issue then.
