### ISSUE TITLE
Compilation on OpenBSD

### ISSUE THREAD

**Issue by djermann** [NagiosEnterprises/nrpe#217]
I want to monitor an OpenBSD server and need to compile nrpe on this server. 
I followed the manual for FreeBSD: https://support.nagios.com/kb/article/nrpe-how-to-install-nrpe-v3-from-source-515.html#FreeBSD
However, when I do configure like this:
`./configure --enable-command-args --with-ssl=/usr/local/bin --with-ssl-inc=/usr/local/include/openssl --with-ssl-lib=/usr/local/lib`
I get an error that it does not find the ssl libraries:
`checking for SSL libraries... configure: error: Cannot find ssl libraries`

How can I compile nrpe on OpenBSD with SSL?

**Comment by sawolf** [comment]
Hi @djermann,

I know this is a bit of a late response, but were you able to figure out the issue (possibly from a Unix users' group or similar)? I don't have very much experience with FreeBSD, nor any with OpenBSD, but if you know what was wrong with that documentation, I should be able to update it.

**Comment by Starow** [comment]
Seems the pull request #276 fix that issue.

On BSD 7.2:
 ```bash
 ./configure --enable-command-args --with-ssl=/usr/bin/openssl --with-ssl-inc=/usr/include/openssl --with-ssl-lib=/usr/lib 
 ```
 
 ```
 ls /usr/lib | grep libssl
libssl.a
...
``` 

without the patch, still getting checking for SSL libraries... configure: error: Cannot find ssl libraries.
