### ISSUE TITLE
Tarballs for 4.0.1, 4.0.2

### ISSUE THREAD

**Issue by thesamesam** [NagiosEnterprises/nrpe#234]
Hi,

It's not clear if 4.0.2 has been released yet. I assume 4.0.1 has because its successor has a changelog too.

Would you mind making a release with the security fixes in 4.0.2 soon? It's easier for distributions if there's an actual release rather than to cherrypick commits.

**Comment by sawolf** [comment]
Hi, thanks for the follow-up!

I still need to do the 4.0.2 release, sorry for any confusion. I'll try to get that in today.

**Comment by thesamesam** [comment]
No problem, thank you!
