### ISSUE TITLE
Error: Request packet had invalid CRC32

### ISSUE THREAD

**Issue by majed17** [NagiosEnterprises/nrpe#236]
Peace, server is Gentoo nrpe v4, and today client became Ubuntu 20 so also nrpe v4..nagios is not reporting any errors but on Ubuntu i see:
```

May  8 14:36:07 SFTP nrpe[73956]: Client request from 10.10.10.12 was invalid, bailing out...
May  8 14:36:47 SFTP nrpe[73969]: Error: Request packet had invalid CRC32.
```
what does this mean?

**Comment by sawolf** [comment]
Hi @majed17. From what I remember, there are two reasons this can happen:

1. There's a mismatch between client/server versions (unlikely, given what you said), or
2. The passwords/cryptographic protocols are mismatched. You can check these in nrpe.cfg (for the server) or check_nrpe.cfg (for the client).

If these all match up and you're still having issues after restarting NRPE, let me know and we can look into it further.

**Comment by majed17** [comment]
well, the ssl options are preceded with #, and i tried restarting nrpe on the server too

**Comment by Thraze** [comment]
Hi all, I have the same issue - also on Gentoo.

Both servers have net-analyzer/nrpe-4.0.0 installed. The client says this:
```
Error: Request packet had invalid CRC32.
Client request from XXX.XXX.XXX.XXX was invalid, bailing out...
```

My monitoring server which runs the check_nrpe says this:

```
Remote XXX.XXX.XXX.XXX accepted a version 2 packet
Remote XXX.XXX.XXX.XXX does not support version 3/4 packets
```

Funny part is, it still works. I get the correct and same nrpe outputs regardless of nrpe version (2, 3 or 4). Maybe the warning is shown wrongly or maybe there is an internal fallback to version 2?

**Comment by sawolf** [comment]
@Thraze, your specific issue was something we noticed with NRPE 4.0.0, and it should be fixed in the latest release (4.0.3), and it was as you said - the newer protocols were always failing, but the automatic retry using v2 would work.

@majed17, I suppose I should have asked - are you getting correct check results from running check_nrpe? If you're seeing the same behavior as @Thraze then I recommend the same fix (upgrading to latest).

**Comment by Thraze** [comment]
@sawolf 
Thanks for the reply. Good to know. Currently NRPE 4.0.0 is the latest stable version for gentoo and not even a "test"-ebuild for 4.0.3 exist yet. But I will just update as soon as possible.

**Comment by majed17** [comment]
./check_nrpe -H 10.10.10.12 -c check_cpu
OK - user: 1.14, nice: 0.50, sys: 0.74, iowait: , irq: 0.50, softirq:  idle: 99.55 | 'user'=1.14 'nice'=0.50 'sys'=0.74 'softirq'= 'iowait'= 'irq'=0.50 'idle'=99.55

**Comment by sawolf** [comment]
@majed17, that output looks okay to me (check_cpu may have missing performance data, but the NRPE parts seem fine). Am I okay to close the issue?

**Comment by majed17** [comment]
as mentioned it looks okay to even nagios yet Error: Request packet had invalid CRC32 are still on the client side...

**Comment by sawolf** [comment]
Just to be clear - you're still receiving this after upgrading both the Gentoo server and the Ubuntu client to NRPE v4.0.3?

**Comment by majed17** [comment]
man when 4.0.3 will be available in gentoo, i'll test, so until then..

**Comment by sawolf** [comment]
Thanks for clarifying. I'm going to close this issue for now. If either of you still have issues after upgrading to v4.0.3, leave a response here and we can re-open the issue.

**Comment by majed17** [comment]
i have a resolution

**Comment by nrotun** [comment]
@majed17 do you have a fix?
Can you please provide information on the fix?

**Comment by majed17** [comment]
4.0.3 is long available on gentoo, you just have to install it
