### ISSUE TITLE
allowed_hosts doesn't work, if one of the hostnames can't be resolved by dns

### ISSUE THREAD

**Issue by Foxeronie** [NagiosEnterprises/nrpe#24]
Hi!

When you define a hostname at "allowed_hosts" which can't be resolved by dns, all the other allowed_hosts can't request checks.

---------------------------
Startup:
Allowing connections from: notavalidhost.domain.de,icinga-wn04.domain.de,icinga-wn05.domain.de

---------------------------
nslookup notavalidhost
Server:		our.dns.server.xxx
Address:	our.dns.server.xxx#53

** server can't find stupidhost: NXDOMAIN

--------------------------
nslookup icinga-wn04
Server:		our.dns.server.xxx
Address:	our.dns.server.xxx#53

Name:	icinga-wn04.domain.de
Address: xxx.xxx.194.64

--------------------------
nrpe[7072]: Host xxx.xxx.194.64 is not allowed to talk to us!

When I remove notavalidhost.domain.de from allowed_hosts and make a restart everything is working fine.

Best regards,
Patrick

**Comment by tmcnag** [comment]
Can I ask you to specify the NRPE version that exhibits this behavior?

`.../path/to/nrpe --version`

**Comment by Foxeronie** [comment]
Sry, sure. :)

NRPE - Nagios Remote Plugin Executor
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 2.15
Last Modified: 09-06-2013

**Comment by jfrickson** [comment]
This should be fixed with commit https://github.com/NagiosEnterprises/nrpe/commit/cd7bb1d6f4d47109d6b88509be921d9eaadd4d71
in branch https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC2
