### ISSUE TITLE
Ubuntu local repository error

### ISSUE THREAD

**Issue by sowmian** [NagiosEnterprises/nrpe#256]
Ign:1 http://10.7.77.213/repos focal InRelease
Ign:2 http://10.7.77.213/repos focal-updates InRelease
Ign:3 http://10.7.77.213/repos focal-backports InRelease
Ign:4 http://10.7.77.213/repos focal-security InRelease
Err:5 http://10.7.77.213/repos focal Release
  404  Not Found [IP: 10.7.77.213 80]
Err:6 http://10.7.77.213/repos focal-updates Release
  404  Not Found [IP: 10.7.77.213 80]
Err:7 http://10.7.77.213/repos focal-backports Release
  404  Not Found [IP: 10.7.77.213 80]
Err:8 http://10.7.77.213/repos focal-security Release
  404  Not Found [IP: 10.7.77.213 80]
Reading package lists... Done
E: The repository 'http://10.7.77.213/repos focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://10.7.77.213/repos focal-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://10.7.77.213/repos focal-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://10.7.77.213/repos focal-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by sawolf** [comment]
Hi @sowmian. Thanks for reaching out. This repository is for issues related to NRPE. If you need help with setting up a local Ubuntu package repository, I would recommend reaching out to that community - as far as I know, we don't provide any packaging information or guidelines for this project.
