### ISSUE TITLE
check_procs option -a fails on long command lines due to COLUMNS environment variable

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nrpe#27]
Reported here:

http://tracker.nagios.org/view.php?id=231

Description:

To receive a list of processes the check_procs plug-in uses:

```bash
/bin/ps axwo 'stat uid pid ppid vsz rss pcpu etime comm args'
```

ps limits its output in regard to the current value of the environment variable COLUMNS. If COLUMNS is set to a small value and the command line arguments of the process is very long (e.g. >1000 characters for a java command with many properties), a required command line argument (-a option) might not be found.

Additional Information:

Debugging becomes tricky as the value of COLUMNS depends on the current environment, when NRPE/check_procs is started. If the NRPE Daemon is started by init, the COLUMNS value might be a lot smaller (96 in my case) than if NRPE Daemon is restarted manually using /etc/init.d/nrpe restart. Actually it depends on the current xterm/putty windows size if the check turns green after a manual restart or not.

**Comment by ssaxnagios** [comment]
More info here:

http://christoph-probst.com/article.php/20110718143604605

**Comment by jfrickson** [comment]
Fixed with commit https://github.com/nagios-plugins/nagios-plugins/commit/75852cf05fbade427dc769a8be87b4fc0c46e3c7
on branch https://github.com/nagios-plugins/nagios-plugins/tree/maint
