### ISSUE TITLE
nrpe 4.1: configuration line length issue?

### ISSUE THREAD

**Issue by swiedernix** [NagiosEnterprises/nrpe#274]
Hello,

I've successfully compiled nrpe-4.1.0 from source code on RHEL9.1

We're using an allow_hosts statement containing ALL our monitoring nodes, approx.  6107 characters.
this works fine with nrpe 3.x

but with nrpe 4.x I get an error after nrpe start:   add_ipv4_to_acl: Error, ip-address >10.25.30< bad state

I couldn't find any malformed character/tabs/newlines ... so I simply deleted all content after this IP address,
which reduces the line length to 2037 characters  - and voila: problem is solved!

now if I add two more IP addresses - I get the same error again.

anybody facing the same issue?

thanks
,
Stefan

**Comment by tatref** [comment]
Could you group servers into networks?

Not sur if this is the issue, but MAX_INPUT_BUFFER is 2048:

https://github.com/NagiosEnterprises/nrpe/blob/65ebf94e3cf46ac39d0fc96439a3831b98b4a506/include/common.h.in#L62

**Comment by swiedernix** [comment]
Thanks @tatref , I will group our systems into multiple allowed_hosts statements to fix this issue.
