### ISSUE TITLE
nrpe_user/nrpe_group not obeyed in el7?

### ISSUE THREAD

**Issue by spicysomtam** [NagiosEnterprises/nrpe#28]
I see with nrpe installed from epel rpm's that startup is very different because of systemd changes.

For all our el4/5/6 systems nrpe.cfg is obeyed for nrpe_user and nrpe_group, but because of the startup on el7 its based on /usr/lib/systemd/system/nrpe.service. So we tweak this file (change nrpe to something else). Then reload systemctl, and then restart nrpe. Thats all good, but maybe some documentation updates are needed or the changes need to be communicated? I did not find anything in the rpm about these changes.

```
# cat /usr/lib/systemd/system/nrpe.service
[Unit]
Description=NRPE
After=network.target
Requires=network.target

[Service]
Type=forking
User=nrpe
Group=nrpe
EnvironmentFile=/etc/sysconfig/nrpe
ExecStart=/usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d $NRPE_SSL_OPT

[Install]
WantedBy=multi-user.target

# systemctl daemon-reload
# systemctl restart nrpe
```

**Comment by martbhell** [comment]
Only modifying /usr/lib/systemd/system/nrpe.service is not enough as the file will get overwritten (OK I only tried with a "yum reinstall").

The nrpe.service is not listed as a config file in the rpm.

Not sure what would be the best way.
Change User to %i and allow setting this manually?

<pre>
# rpm -q -c -l nrpe-2.15-7.el7
/etc/nagios/nrpe.cfg
/etc/sysconfig/nrpe
/usr/lib/tmpfiles.d/nrpe.conf
</pre>

**Comment by dmick** [comment]
The problem here is that the .service file specifies a non-root user, so that nrpe can't itself drop privileges, right?  Should the unit file either specify root/root or not specify anything for user/group?

**Comment by rubenk** [comment]
root/root is the default, so the unit file doesn't have to specify it.

This is a downstream issue since Fedora / EPEL ships its own service file.
I see @dmick has already opened https://bugzilla.redhat.com/1318773. Sadly, the maintainer is not very responsive to bug reports.

I'm not sure what the best fix is. We could let nrpe drop its own privileges from root to the user specified in nrpe.cfg, but technically I don't think nrpe needs to start as root in the first place.

@martbhell The best way to override the User= and Group= settings in the service file is with a drop-in (`systemctl edit nrpe.service`)

**Comment by ktdreyer** [comment]
I'll try to get EPEL to be more responsive to that BZ :( I guess the ideal here would be to have the .service file in nrpe upstream, and simply have EPEL consume that directly.

**Comment by dmick** [comment]
Separate the service file and the daemon?  Is that a thing?

**Comment by jfrickson** [comment]
NPRE 3.0 provides a .service and .socket file with user and group specified. In addition to systemd, it also includes init and inetd files for BSD, SysV, upstart, launchd, smf 10/11 and openrc.

**Comment by jfrickson** [comment]
Hmm, I should have closed this along with my last comment. Closing now.

**Comment by ckujau** [comment]
With that issue closed, can the [NOTE](https://github.com/NagiosEnterprises/nrpe/blob/master/sample-config/nrpe.cfg.in#L77) about ```inetd``` and ```xinetd``` configurations be extended to ```systemd``` to make clear that ```nrpe_user=``` and ```nrpe_group``` is ignored? (and possibly other init systems, if needed).
