### ISSUE TITLE
NRPE :  "deprecated" removed

### ISSUE THREAD

**Issue by jbeaujour** [NagiosEnterprises/nrpe#280]
Hello
The comment "deprecated" was removed from the nrpe project on github on September 6.
Does this mean officially coming back to life?
THANKS

**Comment by ericloyd** [comment]
Oh God, I hope not.  What a horrible agent to manage and configure!

**Comment by sawolf** [comment]
Hi @jbeaujour, thanks for reaching out.

Yes, we intend to support NRPE going forward. We didn't really want to make noise about it until we had a new release ready to go, but we'll be keeping the project alive for the foreseeable future.
