### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [NagiosEnterprises/nrpe#29]
The function "[printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different design will be needed for your function "[alarm_handler](https://github.com/NagiosEnterprises/nrpe/blob/3a3cdd0e9e1cc7ca2e12cc06dfc2f3ac7f6464d5/src/check_nrpe.c#L451 "Reconsider signal handling implementation.")".

**Comment by tmcnag** [comment]
I'll defer to @jfrickson for the final decision, but since this handler is used to exit on a timeout I can't see the harm in using a synchronous function.

**Comment by jfrickson** [comment]
Fixed in commit https://github.com/NagiosEnterprises/nrpe/commit/ce6c77565074b11ac83de3211da7194362fce8cf

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/NagiosEnterprises/nrpe/blob/ce6c77565074b11ac83de3211da7194362fce8cf/src/nrpe.c#L1954 "Update candidate: child_sighandler()") left over?
