### ISSUE TITLE
NRPE Character Limit

### ISSUE THREAD

**Issue by hooolden** [NagiosEnterprises/nrpe#32]
Since our primary development platform for NRPE is GitHub, I am going to move the issue over here regarding the 1024 byte payload limit.  

The initial issue was opened on the tracker here: http://tracker.nagios.org/view.php?id=564
A forum thread regarding the issue can be found here: https://support.nagios.com/forum/viewtopic.php?f=34&t=35082&p=156472&hilit=nrpe#p156472
Another highly referenced forum thread: https://support.nagios.com/forum/viewtopic.php?f=34&t=25221
A potential patch was provided here:https://web.archive.org/web/20120309192252/http://labs.opsview.com/2008/08/enhancing-nrpe-for-large-output
Another post outlining the issue: http://serverfault.com/questions/613288/truncating-return-data-as-it-is-bigger-then-nrpe-allows

There is also a branch of NRPE by abrist that patches this as well.

**Comment by tmcnag** [comment]
To summarize, the default packet size is 1024 bytes which is in some cases not long enough and causes status output truncation.  This should either be configurable or placed so high as to be reasonably safe against overflow.

**Comment by florian-asche** [comment]
+1

**Comment by jfrickson** [comment]
Apparently, I forgot to comment on this issue. Sorry. On November 13, I made two commits. nrpe and nrpe_client will now support either the current protocol (for backward compatibility), or protocol version 3 which allows up to 64K.

This is in the nrpe-2-16-RC2 branch:
https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC2

**Comment by jfrickson** [comment]
No problems or side-effects reported, so I'm closing the issue.
