### ISSUE TITLE
Faults never see before

### ISSUE THREAD

**Issue by uncelvel** [NagiosEnterprises/nrpe#33]
hi everyone
I have 3 Server. 1 Nagios Core 2 Nagios Remote
1 one of 2 Nagios Remote have fault when i make all nrpe
___________________________________________________________
And the nagios Remote serrver i setup now is faults have OUTPUT 
                                       _________________________________________

...............................
 General Options:
 -------------------------
 NRPE port:    5666
 NRPE user:    nagios
 NRPE group:   nagios
 Nagios user:  nagios
 Nagios group: nagios

Review the options above for accuracy.  If they look okay,
type 'make all' to compile the NRPE daemon and client.

[canhdx@DANANG nrpe-2.13]$ sudo make all
cd ./src/; make ; cd ..
make[1]: Entering directory `/home/canhdx/nrpe-2.13/src'
gcc -g -O2 -I/usr/include/openssl -I/usr/include -DHAVE_CONFIG_H -o nrpe nrpe.c utils.c acl.c -L/usr/lib64  -lssl -lcrypto -lnsl   
nrpe.c: In function ‘main’:
nrpe.c:218:7: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
   meth=SSLv23_server_method();
       ^
gcc -g -O2 -I/usr/include/openssl -I/usr/include -DHAVE_CONFIG_H -o check_nrpe check_nrpe.c utils.c -L/usr/lib64  -lssl -lcrypto -lnsl 
check_nrpe.c: In function ‘main’:
check_nrpe.c:126:7: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
   meth=SSLv23_client_method();
       ^
make[1]: Leaving directory `/home/canhdx/nrpe-2.13/src'

*** Compile finished ***

If the NRPE daemon and client compiled without any errors, you
can continue with the installation or upgrade process.

Read the PDF documentation (NRPE.pdf) for information on the next
steps you should take to complete the installation or upgrade.
___________________________________________________________
And the nagios Remote serrver i setup before not faults is OUTPUT 
                                       _________________________________________

.......
*** Configuration summary for nrpe 2.13 11-11-2011 ***:

 General Options:
 -------------------------
 NRPE port:    5666
 NRPE user:    nagios
 NRPE group:   nagios
 Nagios user:  nagios
 Nagios group: nagios

Review the options above for accuracy.  If they look okay,
type 'make all' to compile the NRPE daemon and client.

[canhdx@KHANHHOA_MO nrpe-2.13]$ sudo make
cd ./src/; make ; cd ..
make[1]: Entering directory `/home/canhdx/nrpe-2.13/src'
gcc -g -O2 -I/usr/include/openssl -I/usr/include -DHAVE_CONFIG_H -o nrpe nrpe.c utils.c acl.c -L/usr/lib64  -lssl -lcrypto -lnsl   
nrpe.c: In function ‘main’:
nrpe.c:218: warning: assignment discards qualifiers from pointer target type
gcc -g -O2 -I/usr/include/openssl -I/usr/include -DHAVE_CONFIG_H -o check_nrpe check_nrpe.c utils.c -L/usr/lib64  -lssl -lcrypto -lnsl 
check_nrpe.c: In function ‘main’:
check_nrpe.c:126: warning: assignment discards qualifiers from pointer target type
make[1]: Leaving directory `/home/canhdx/nrpe-2.13/src'

*** Compile finished ***

If the NRPE daemon and client compiled without any errors, you
can continue with the installation or upgrade process.

Read the PDF documentation (NRPE.pdf) for information on the next
steps you should take to complete the installation or upgrade.
_______________________________________________
Is SSL? because i check in nagios Core 
[canhdx@KHANHHOA_MO ~]$ /usr/local/nagios/libexec/check_nrpe -H 10.58.37.176 -n
NRPE v2.13
OK ------------------ but 
[canhdx@KHANHHOA_MO nrpe-2.13]$ /usr/local/nagios/libexec/check_nrpe -H 10.58.37.176 
CHECK_NRPE: Socket timeout after 10 seconds.
>>>>>>> Faults

**Comment by jfrickson** [comment]
Can you check this branch: https://github.com/NagiosEnterprises/nrpe/tree/nrpe-2-16-RC2
The compile warnings are fixed in that branch, I think. Also, there were a lot of changes to SSL/TLS. See the README.SSL.md file.

**Comment by uncelvel** [comment]
Thank @jfrickson  answer my question  . This fault can be skip and continues next step without problem. I have try and successfully
