### ISSUE TITLE
check_nrpe plugin - config file might be handy for newer SSL stuff

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/nrpe#34]
From the server that is executing check_nrpe plugin, the command line arguments are getting quite long, for example:

```
./check_nrpe -H 192.168.10.219 -C /usr/local/nagios/etc/ssl/client_certs/nag_serv.pem -K /usr/local/nagios/etc/ssl/client_certs/nag_serv.key -A /usr/local/nagios/etc/ssl/ca/ca_cert.pem -c check_mem
```

It might be handy if we allow the check_nrpe plugin to use a config file for any settings. It might look at a default file name/location, but also the option to define what config file could be used as this might help in multi tenant scenarios.

**Comment by jfrickson** [comment]
Code has been added to nrpe-3.0-RC2.
