### ISSUE TITLE
NRPE 3.0 does not allow arguments with dont_blame_nrpe=1

### ISSUE THREAD

**Issue by Saford91** [NagiosEnterprises/nrpe#44]
After upgrading to 3.0, I can no longer pass arguments to NRPE commands. The log indicates:

nrpe[32827]: Error: Request contained command arguments!
nrpe[32827]: Client request from  was invalid, bailing out...

**Comment by lgroschen** [comment]
Did you configure with
`./configure --enable-command-args`

when compiling?

**Comment by Saford91** [comment]
No, I hadn't realized this changed. Was this part of the two security holes that were patched in 3.0? Anyways, I rebuilt with that option and now I get a different error. For example, If I run:

`/usr/local/nagios/libexec/check_nrpe -H localhost -c 'check_node_ping' -a super001`

I get:

`NRPE: Command 'check_node_ping!super001' not defined`

They syntax of the example commands that take arguments in the conf file look the same to me, so I'm not sure what went wrong. My command definition is:

`command[check_node_ping]=/usr/local/nagios/libexec/check_ping -H $ARG1$ -w 100.0,20% -c 500.0,60% -p 5`

**Comment by Saford91** [comment]
My mistake, it definitely says to configure with --enable-command-args in the config file.

**Comment by lgroschen** [comment]
Hope you get it working!  Check in over at [support.nagios.com/forum](https://support.nagios.com/forum) if you need any assistance- you don't need to be a customer to get general support.

**Comment by Saford91** [comment]
Thanks, I'll check it out. For now I will go back to 2.15.

**Comment by jfrickson** [comment]
It sounds like you have it figured out, so I'm closing this issue. If you still have a problem, post in the forum or here.
