### ISSUE TITLE
Version string contains name

### ISSUE THREAD

**Issue by spfjpl** [NagiosEnterprises/nrpe#45]
While testing the new 3.0 release, I noticed the following oddity:

$ /usr/lib64/nagios/plugins/check_nrpe -H localhost
NRPE vnrpe-3.0

This is compared to the result for version 2.15:

$ /usr/lib64/nagios/plugins/check_nrpe -H localhost
NRPE v2.15

I assume the name shouldn't be part of the version string?

Comparing the sources:

nrpe-2.15/configure:PKG_VERSION="2.15"
nrpe-2.15/include/common.h:#define PROGRAM_VERSION "2.15"

nrpe-3.0/configure.ac:AC_INIT([nrpe],[nrpe-3.0],[nagios-users@lists.sourceforge.net],[nrpe],[https://www.nagios.org/downloads/nagios-core-addons/])
nrpe-3.0/configure.ac:PKG_VERSION="nrpe-3.0"
nrpe-3.0/include/common.h.in:#define PROGRAM_VERSION "nrpe-3.0"

**Comment by jfrickson** [comment]
Fixed in master and maint branches.

**Comment by glensc** [comment]
- +1 for fixing it
- -1 for keeping autogenerated content like `configure` in git
