### ISSUE TITLE
nrpe 3 incompatible with nrpe 2

### ISSUE THREAD

**Issue by lrupp** [NagiosEnterprises/nrpe#49]
I updated the check_nrpe to version 3.0 on my monitoring server and tried to reach out to the clients that still run nrpe 2.15.

Even if I adapt the monitoring config to use the "-2" option, the old nrpe daemons can not be reached to the new check_nrpe.

Example command definition in Nagios:

 define command{
        command_name nrpe-check_ntp_with_port
        command_line $USER1$/check_nrpe $ARG1$ -2 -t 120 -c check_ntp
 }

Output from the check in the WebUI:
 CHECK_NRPE: Receive header underflow - only 0 bytes received (4 expected).

**Comment by lrupp** [comment]
Sorry, my own fault: applied an old patch on top of the current code base that does simply the wrong stuff :-(

**Comment by box293** [comment]
Great to hear you were able to quickly resolve this.

**Comment by lrupp** [comment]
Am 2016-08-10 23:20, schrieb Troy Lea:
> Great to hear you were able to quickly resolve this.

Jip: was an old patch that applied smoothly but was not useful any more 
with the new code base ;-)

I have a few more minor patches that I will submit against your github 
repo in a few days. Mostly cosmetic, but let's see...

Thanks for taking care of your software so quickly, really appreciated!

With kind regards,
Lars

**Comment by sinjihn** [comment]
hey sorry to necro this but how did you uninstall the nagios 2 without destroying 3?

**Comment by sinjihn** [comment]
actually nagios 2 isn't even installed anymore - I did a fresh install and still get this issue.

**Comment by box293** [comment]
It's probably best to open a forum thread here to help troubleshoot your problem:

https://support.nagios.com/forum/viewforum.php?f=7

**Comment by jerbowes** [comment]
Arg.. This is my exact problem getting nrpe 3.0.1 running on my Linux OEL 6.8 server and getting 'CHECK_NRPE: Receive header underflow - only 0 bytes received (4 expected).'

**Comment by box293** [comment]
It's probably best to open a forum thread here to help troubleshoot your problem:

https://support.nagios.com/forum/viewforum.php?f=7
