### ISSUE TITLE
nrpe.spec file outdated, missing install-daemon-config install target

### ISSUE THREAD

**Issue by scottwilkerson** [NagiosEnterprises/nrpe#50]
reported by kaushalshriyan @ https://support.nagios.com/forum/viewtopic.php?f=7&t=39776

I am seeing this issue make: *** No rule to make target `install-daemon-config'. Stop. while i run rpmbuild -ba nrpe.spec while creating NRPE version 3 rpm binaries for CentOS 6.x.

rpmbuild -ba nrpe.spec -> https://paste.fedoraproject.org/406628/09947601/
cat nrpe.spec -> https://paste.fedoraproject.org/406629/94804147/
cat /etc/redhat-release
CentOS release 6.7 (Final)

**Comment by jfrickson** [comment]
Fix is in 'maint' branch at https://github.com/NagiosEnterprises/nrpe/tree/maint via commit https://github.com/NagiosEnterprises/nrpe/commit/1e0003831313825beb73cb8fd40d2be872bd0708

**Comment by shriyankaushal** [comment]
Hi John,

Thanks for the fixing the bug. I will appreciate if you can let me know if it is available to be downloaded and can be used in production.

Regards,

Kaushal

**Comment by jfrickson** [comment]
You can download the tarball at https://github.com/NagiosEnterprises/nrpe/archive/maint.tar.gz

**Comment by shriyankaushal** [comment]
Hi John,

Please find the details -> http://sprunge.us/TMiB after following your email instructions. The issue still persists which are as below :-

Processing files: nrpe-3.0-1.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/etc/init.d/nrpe
error: File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/usr/sbin/nrpe
error: File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/etc/nagios
error: File not found by glob: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/etc/nagios/*.cfg
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.XDEWYf
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd nrpe-3.0
+ DOCDIR=/root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/usr/share/doc/nrpe-3.0
+ export DOCDIR
+ rm -rf /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/usr/share/doc/nrpe-3.0
+ /bin/mkdir -p /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/usr/share/doc/nrpe-3.0
+ cp -pr Changelog LEGAL README.md README.SSL.md SECURITY.md /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/usr/share/doc/nrpe-3.0
+ exit 0
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/usr/share/doc/nrpe-3.0


RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/etc/init.d/nrpe
    File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/usr/sbin/nrpe
    File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/etc/nagios
    File not found by glob: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/etc/nagios/*.cfg
    %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0-1.x86_64/usr/share/doc/nrpe-3.0

Regards,

Kaushal

**Comment by jfrickson** [comment]
@shriyankaushal I made quite a few changes to nrpe.spec that should address all your problems. Try again from scratch.

**Comment by jfrickson** [comment]
Reporter says it is now working properly.

**Comment by rcanete** [comment]
Hi John,

Good day.

I tried to create a rpm package for rhel 6.x but to failed. I tried below compilation parameters and building it.

./configure --with-opsys=linux --with-dist-type=rh  --with-init-type=openrc --with-inetd-type=xinetd

rpmbuild -ba nrpe.spec

Errors:
Group nagios already exists
User nagios already exists
cd ./src/; make install
make[1]: Entering directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
make install-plugin
make[2]: Entering directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
/usr/bin/install -c -m 755 -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin
/usr/bin/install -c -m 755 ../uninstall /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin/nrpe-uninstall
/usr/bin/install -c -m 775 -o nagios -g nagios -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/lib/nagios/plugins
/usr/bin/install -c -m 775 -o nagios -g nagios -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/lib/nagios/plugins
/usr/bin/install -c -m 775 -o nagios -g nagios check_nrpe /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/lib/nagios/plugins
make[2]: Leaving directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
make install-daemon
make[2]: Entering directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
/usr/bin/install -c -m 755 -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin
/usr/bin/install -c -m 755 ../uninstall /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin/nrpe-uninstall
/usr/bin/install -c -m 755 nrpe /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin
/usr/bin/install -c -m 755 -o nagios -g nagios -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/var/log/nagios
make[2]: Leaving directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
make[1]: Leaving directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
/usr/bin/install -c -m 775 -o nagios -g nagios -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/nagios
/usr/bin/install -c -m 644 -o nagios -g nagios sample-config/nrpe.cfg /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/nagios
/usr/bin/install -c -m 644 startup/rh-upstart-init /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init/nrpe.conf
/usr/bin/install: cannot create regular file `/root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init/nrpe.conf': No such file or directory
initctl reload-configuration
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id /root/rpmbuild/BUILD/nrpe-3.0.1
extracting debug info from /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin/nrpe
extracting debug info from /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/lib/nagios/plugins/check_nrpe
307 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: nrpe-3.0.1-1.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init.d/nrpe
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/nagios
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.vmXql9
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd nrpe-3.0.1
+ DOCDIR=/root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1
+ export DOCDIR
+ rm -rf /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1
+ /bin/mkdir -p /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1
+ cp -pr Changelog LEGAL README.md README.SSL.md SECURITY.md /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1
+ exit 0
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1


RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init.d/nrpe
    %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/nagios
    %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1

Thanks,

Ronald Canete
