### ISSUE TITLE
conflicting command line interpreters with check_cpu_stats.sh

### ISSUE THREAD

**Issue by mcapra** [NagiosEnterprises/nrpe#51]
Most commonly on Ubuntu where /bin/sh links to dash, users are experiencing errors with the check_cpu_stats.sh script out-of-the-box. It is suggested that the shebang be changed to #!/bin/bash

**Comment by jfrickson** [comment]
check_cpu_stats.sh is not part of the official Nagios Plugins. It's probably from the exchange (https://exchange.nagios.org/index.php?option=com_mtree&task=search&Itemid=74&searchword=check_cpu_stats), so we have no control over it.
