### ISSUE TITLE
strtok and strtok_r problem

### ISSUE THREAD

**Issue by jobst** [NagiosEnterprises/nrpe#54]
This took a fair while to debug.
When I run "configure --sysconfdir ..... --enable-ssl" I can see the following lines:

> checking for strstr... yes
> checking for strtoul... yes
> checking for strtok_r... yes
> checking for initgroups... yes`

but when I add a debug line using "syslog(..)" to the function "parse_allowed_hosts()" as such:

> #ifdef HAVE_STRTOK_R
>   syslog(LOG_INFO,"parse_allowed_hosts strtok_r\n");
>   tok = strtok_r(hosts, delim, &saveptr);
> #else
>   syslog(LOG_INFO,"parse_allowed_hosts strtok\n");
>   tok = strtok(hosts, delim);
> #endif`

then in the syslog I see:

> Aug 29 14:42:37 NRPE_CLIENT nrpe[3200]: parse_allowed_hosts strtok
 
which, off course, indicates that strtok is used although strtok_r is available.

This, off course, has a massive problem for me as "strtok" is NOT re-entrant and leads to problems I have initially described [here.](https://support.nagios.com/forum/viewtopic.php?f=7&t=39960)

Jobst

**Comment by jfrickson** [comment]
Fixed in 'maint' branch via commit https://github.com/NagiosEnterprises/nrpe/commit/4e52e17aaf1fecf0a2a95dd30d015333d618b30c. Fix will be in the next bug-fix release coming in early Septembver.
