### ISSUE TITLE
Please consider writing a str_split and using that instead of strtok/strtok_r

### ISSUE THREAD

**Issue by jobst** [NagiosEnterprises/nrpe#55]
I have had a problem as described [here](https://support.nagios.com/forum/viewtopic.php?f=7&t=39960) and I already submitted a bug to the bug tracker about this.

However, it might be better to write a str_split function and use that instead of using strtok (which is not re-entrant and thus leads to problems). While this STILL uses strtok is does not need to be re-entrant as it is one function call. It also works on the system in problem.

Consider to use (see below for further code fragments in how to apply):
> char** str_split(char* a_str, const char a_delim)
> {
>   char** result    = 0;
>   size_t count     = 0;
>   char* tmp        = a_str;
>   char* last_comma = 0;
>   char delim[2];
>   delim[0] = a_delim;
>   delim[1] = 0;
>   /* Count how many elements will be extracted. */
>   while (*tmp) {
>     if (a_delim == *tmp) {
>       count++;
>       last_comma = tmp;
>     }
>     tmp++;
>   }
>   /* Add space for trailing token. */
>   count += last_comma < (a_str + strlen(a_str) - 1);
>   /* Add space for terminating null string so caller
>      knows where the list of returned strings ends. */
>   count++;
>   result = malloc(sizeof(char*) * count);                                                                              
>   if (result) {
>     size_t idx  = 0;
>     char* token = strtok(a_str, delim);
>     while (token) {
>       assert(idx < count);
>       *(result + idx++) = strdup(token);
>       token = strtok(0, delim);
>     }
>     assert(idx == count - 1);
>     *(result + idx) = 0;
>   }
>   return result;
> }

which then can be called in 
I added a few more debugging statements to see the flow.
When you use it this way, the function adds correctly all items in the allowed_hosts list.

> void parse_allowed_hosts(char *allowed_hosts) {
>   char *hosts = strdup( allowed_hosts); /* Copy since strtok* modifies original */
>   char *saveptr;
>   char *tok;
>   const char delim[2] = ",\0";
>   char *trimmed_tok;
>   char** tokens;
> 
>   tokens = str_split(hosts, ',');
>   if (tokens)
>   {
>     int i;
>     for (i = 0; *(tokens + i); i++)
>     {
>       syslog(LOG_INFO, "Current Token, trying one >%s<\n", *(tokens + i));
>       one=add_ipv4_to_acl(*(tokens + i));
>       syslog(LOG_INFO,"parse_allowed_hosts: one >%d<\n", one);
>       if(!one)
>       {
>         syslog(LOG_INFO,"parse_allowed_hosts: trying two >%s<\n", *(tokens + i));
>         two=add_ipv6_to_acl(*(tokens + i));
>         syslog(LOG_INFO,"parse_allowed_hosts: two >%d<\n", two);
>         if(!two)
>         {
>           syslog(LOG_INFO,"parse_allowed_hosts: trying three >%s<\n", *(tokens + i));
>           three=add_domain_to_acl(*(tokens + i));
>           if(!three)
>           {
>             syslog(LOG_INFO,"Can't add to ACL this record (%s). Check allowed_hosts option!\n",* (tokens + i));
>             syslog(LOG_ERR,"Can't add to ACL this record (%s). Check allowed_hosts option!\n",*(tokens + i));
>           }
>         }
>       }
>       free(*(tokens + i));
>     }
>     free(tokens);                                                                                                                      
>   }
>   free( hosts);
> }

**Comment by jfrickson** [comment]
Because of the way I decided to implement the fix (in commit https://github.com/NagiosEnterprises/nrpe/commit/4e52e17aaf1fecf0a2a95dd30d015333d618b30c) writing a `str_split` function is not necessary.
