### ISSUE TITLE
config.h not included into acl.c

### ISSUE THREAD

**Issue by jobst** [NagiosEnterprises/nrpe#56]
Subject line explains it all: config.h not included into acl.c
NONE of the information that is found in "./include/config.h" is available in "./src/acl.c"

So please, either add the following line in file ./include/acl.h

> #include "config.h"

OR add the following line to ./src/acl.c:

> #include "../include/config.h"

This has been a horrible debugging session, see https://support.nagios.com/forum/viewtopic.php?f=7&t=39960

**Comment by jfrickson** [comment]
Fixed in 'maint' branch via commit https://github.com/NagiosEnterprises/nrpe/commit/4e52e17aaf1fecf0a2a95dd30d015333d618b30c. Fix will be in the next bug-fix release coming in early Septembver.
