### ISSUE TITLE
nrpe.cfg: debug statement needs to be first in file

### ISSUE THREAD

**Issue by jobst** [NagiosEnterprises/nrpe#58]
Hi
The debug declaration in the file nrpe.cfg needs to be higher up, if not FIRST!

Reason: when parsing the file and the debug declaration is too late, the check "if(debug==TRUE)" in functions that are used BEFORE (for example parse_allowed_hosts) returns the incorrect value as it has NOT been declared early enough.

**Comment by jfrickson** [comment]
Fixed in 'maint' branch via commit https://github.com/NagiosEnterprises/nrpe/commit/714a5ab6e7fd979e883e8d3daa412fa692ed8d55
