### ISSUE TITLE
acl.c has no access to the value "debug"

### ISSUE THREAD

**Issue by jobst** [NagiosEnterprises/nrpe#59]
Hi

The evaluation of "if(debug==true)" in acl.c is always incorrect as acl.c does not have access to "int debug".
There needs to be a variable declaration in acl.c like so:

> extern int debug;

This will yield correct output for statements like

> if(debug==TRUE) syslog(LOG_INFO,"debug now has a correct value of >%d<\n",debug);

**Comment by jfrickson** [comment]
Fixed via commit https://github.com/NagiosEnterprises/nrpe/commit/23793bf22a7cf9b12e5113d16b5504b50faaf4ca
