### ISSUE TITLE
Debugging was hard as many "syslog(...)" statements were missing

### ISSUE THREAD

**Issue by jobst** [NagiosEnterprises/nrpe#60]
John

During my last couple of days to find my problem one thing I noticed: missing debug statements.

I have attached two files nrpe.cfg and acl.c that show were I added "syslog(....)" statements to make debugging a little easier. I would have found the bugs earlier wasn't it for the missing syslog(..)'s.

Also, the function show_acl_list should be part of of the printout "if(debug==TRUE)" right AFTER the parsing of the allowed_hosts varaible! It, too, should syslog the information instead of printf them!.

You can easily find the changed/added code by searching /* jobst added/changed */ in both files.
I had to add these to figure out what was wrong.

Please use it so the next poor soul has an easier time!

[twofiles.zip](https://github.com/NagiosEnterprises/nrpe/files/444119/twofiles.zip)

**Comment by jfrickson** [comment]
@jobst I think you uploaded the wrong files. I don't see that comment anywhere, and there was no "if(debug==TRUE)" check after parsing.

**Comment by jobst** [comment]
Attached a new version ... maybe I had too many xterms open and I zipped the wrong ones.
Also, better to check for "jobst".

[SecondAttemptTwoZipFiles.zip](https://github.com/NagiosEnterprises/nrpe/files/446344/SecondAttemptTwoZipFiles.zip)

**Comment by jfrickson** [comment]
Fixed in branch maint via commit https://github.com/NagiosEnterprises/nrpe/commit/23793bf22a7cf9b12e5113d16b5504b50faaf4ca.

Sorry it took so long to get back to this.
