### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by myH2Oservers** [NagiosEnterprises/nrpe#63]
With the following config:

Sep 11 16:30:41 web1 nrpe[28726]: SSL Certificate File: None
Sep 11 16:30:41 web1 nrpe[28726]: SSL Private Key File: None
Sep 11 16:30:41 web1 nrpe[28726]: SSL CA Certificate File: None
Sep 11 16:30:41 web1 nrpe[28726]: SSL Cipher List: ALL:!aNULL:!MD5
Sep 11 16:30:41 web1 nrpe[28726]: SSL Allow ADH: Allow
Sep 11 16:30:41 web1 nrpe[28726]: SSL Client Certs: Don't Ask
Sep 11 16:30:41 web1 nrpe[28726]: SSL Log Options: 0x2f
Sep 11 16:30:41 web1 nrpe[28726]: SSL Version: TLSv1_2 And Above
Sep 11 16:30:41 web1 nrpe[28726]: INFO: SSL/TLS initialized. All network traffic will be encrypted.

NRPE segfaults on requests:
Sep 11 16:30:41 web1 kernel: nrpe[28726]: segfault at 66d18a1d ip 00007f0f6616bdec sp 00007ffe6b93c290 error 4 in libc-2.12.so[7f0f66124000+18a000]

When using one of the 2 example cipher lists no crash happens, when changing it to any other cipher list, for example "ALL:!aNULL:!MD5" the segfault occurs.

System information:
OS: up2date CentOS release 6.8 (Final)
OpenSSL: OpenSSL 1.0.1e-fips 11 Feb 2013
NRPE: 3.0.1
NRPE run through xinetd

**Comment by jfrickson** [comment]
Try using a newer version of OpenSSL and let me know if that helps.

**Comment by jfrickson** [comment]
No response in two months. I'm assuming the requester either found an "operator error", or a newer version of OpenSSL fixed it.
