### ISSUE TITLE
check_nrpe info logging

### ISSUE THREAD

**Issue by nerezz** [NagiosEnterprises/nrpe#64]
check_nrpe constantly logging NOTICE to syslog on successful connect.  I have had to roll back to 2.15 to reduce the logging on my nagios host as I cannot discard INFO syslog on that host for other application requirements.

Would it be possible to change the success logging to ONLY happen when cascading down from a failed? or if Debug option is active?

starting Line 171, or just before final result return in Main()
	if (result != -1)
		syslog(LOG_NOTICE, "Remote %s accepted a Version %d Packet", rem_host, packet_ver);

	return result;

**Comment by nerezz** [comment]
A quickfix for me was to move the last result check to inside the v3 failure re-try as per the attached 
[check_nrpe_NOINFO.patch.txt](https://github.com/NagiosEnterprises/nrpe/files/490332/check_nrpe_NOINFO.patch.txt)

**Comment by jfrickson** [comment]
Would it be acceptable to you if it was logged at LOG_INFO instead of LOG_NOTICE? Or maybe LOG_DEBUG?

**Comment by nerezz** [comment]
Currently, according to the nagios help for [nrpe v3 compatibility](https://support.nagios.com/kb/article.php?id=516), using the -2 option to force v2 protocol connections is supposed to remove the log entries, and v2.15 does not log any successful connections to syslog.  With the new protocol version there are more states to think about as well: (Some ideas about what a successful connection looks like)
V3 first try success (LOG_DEBUG)
V3 failure - Downgrade to V2 success (LOG_INFO)
V2 first try success (LOG_DEBUG) (via using check_nrpe -2)

**Comment by nerezz** [comment]
Some might argue that even a V3 failuer followed by a V2 success could be a LOG_DEBUG too, but I like the idea that you get a LOG_INFO highlighting which older clients you have.  (you can always create a command definition to add the -2 for older clients if that state is too chatty for an environment.. I'll probably do that until I get the bulk of my clients updated to V3)

**Comment by jfrickson** [comment]
Probable fix in place in the maint branch via commit https://github.com/NagiosEnterprises/nrpe/commit/fe006d2556c906de84321188630ab0d25c317cc1

Let me know if that takes care of it for you.
