### ISSUE TITLE
Allow NRPE logging directly rather than requiring use of syslog

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nrpe#65]
> This issue has been automatically migrated from http://tracker.nagios.org/view.php?id=0000419 - Please follow that link for details.
> Originally submitted on 2013-02-05 by mfrost

In our environment, we don't have root access or generally control over how syslog is working on our servers. Because syslog is the means by which NRPE writes out logs, this means that sometimes when troubleshooting we can't see the logs where relevant information goes.

It would be handy to be able to configure NRPE to log all activity directly to a specified log file rather than to syslog (or, I guess conditionally switch where logging goes to).

Thanks

**Comment by Houlistonm** [comment]
This feature would be very nice in my environment as well.  We have a strict separation of host vs application and the host logs are restricted to root users only.

Direct to a log file would be great, some sort of log management would be fantastic.
It would be nice if todays log was always to the same file name (so our ELK stack can follow the log) and on some schedule, move the log to time stamped file, and open a new logfile. 

Thanks

**Comment by jfrickson** [comment]
This is now in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/b8ee0362614a1ca49d8269165ba2140f2c903dd0.

See the commit for a description of how it works.
