### ISSUE TITLE
Solaris 11 detection is broken in configure

### ISSUE THREAD

**Issue by skrueger8** [NagiosEnterprises/nrpe#67]
Hi,

./configure is not able to correctly detect Solaris 11:

```
if test "$dist_type" = solaris -a "$dist_ver" != smf11; then
    $as_echo "#define SOLARIS_10 yes" >>confdefs.h

fi
```

$dist_ver is defined is as:

```
  solaris) :
    dist_ver=`echo $OSTYPE | cut -d'.' -f2` ;; #(
```

OSTYPE seems to be only defined when using bash

```
me@solaris11.3:~ $ echo $OSTYPE
solaris2.11
```

but not when using /bin/sh (the default shell for configure):

```
me@solaris11.3:~ $ echo $OSTYPE

```

So checking for 'smf11' is wrong, and $OSTYPE is undefined when not using bash...

**Comment by jfrickson** [comment]
I didn't know that. I'll change it to use `uname -r` which seems to provide the info I need. I'll also have to check into AIX and HP-UX. I was using `$OSTYPE` for those also.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/98e253de294c553abf2f6657b74540a7d7162202
Should be release as version 3.0.2 hopefully sometime in November.
