### ISSUE TITLE
A future version of Solaris will have b64_decode in string.h/libc

### ISSUE THREAD

**Issue by skrueger8** [NagiosEnterprises/nrpe#68]
Hi,

a future version of Solaris (Solaris 12) will include a b64_decode function in string.h/libc, which will conflict with nrpe's own b64_decode() in include/utils.h and src/utils.c.

```
Standard C Library Functions                                    b64_encode(3C)

NAME
       b64_encode,  b64_decode,  b32_encode,  b32_decode - encode and decode a
       string in base64 or base32

SYNOPSIS
       #include <string.h>

       ssize_t b64_encode(char restrict *outbuf, size_t outbufsz,
                const void restrict *inbuf, size_t inbufsz,
                const char *alphabet, uint64_t flags);

       ssize_t b64_decode(void *outbuf, size_t outbufsz,
                const char *inbuf, const char *alphabet, uint64_t flags);

       ssize_t b32_encode(char restrict *outbuf, size_t outbufsz,
                const void restrict *inbuf, size_t inbufsz,
                const char *alphabet, uint64_t flags);

       ssize_t b32_decode(void *outbuf, size_t outbufsz,
                const char *inbuf, const char *alphabet, uint64_t flags);

       const char *BASE64_URL_ALPHABET;
       const char *BASE32_HEX_ALPHABET;
```

Renaming nrpe's b64_decode to nrpe_b64_decode (or smth else) should make this code compile again.

PS: is b64_decode() dead code? it's not used anywhere in nrpe/check_nrpe...

**Comment by jfrickson** [comment]
You appear to be correct. b64_decode does not appear to be used anywhere. I'll probably remove the function from utils.[hc].

When will Solaris 12 be coming out? There will probably be other issues, as well.

**Comment by skrueger8** [comment]
I have no idea when Solaris 12 comes out, but we're in the private beta and nrpe builds fine on Solaris 12 when b64_decode  is renamed or removed, there are some compiler warnings though (I'm building with Oracle Developer Studio 12.5):

* "./nrpe.c", line 241: warning: initializer does not fit or is out of range: 2148535295

```
   241          int       ssl_opts = SSL_OP_ALL | SSL_OP_SINGLE_DH_USE, vrfy;
```

ssl_opts has to be long, not int; see man SSL_CTX_set_options:

```
OpenSSL                                          SSL_CTX_set_options(3openssl)

NAME
       SSL_CTX_set_options, SSL_set_options, SSL_CTX_clear_options,
       SSL_clear_options, SSL_CTX_get_options, SSL_get_options,
       SSL_get_secure_renegotiation_support - manipulate SSL options

SYNOPSIS
        #include <openssl/ssl.h>

        long SSL_CTX_set_options(SSL_CTX *ctx, long options);
```

* "./nrpe.c", line 264: warning: implicit function declaration: RAND_status
* "./nrpe.c", line 265: warning: implicit function declaration: RAND_file_name
* "./nrpe.c", line 266: warning: implicit function declaration: RAND_load_file
* "./nrpe.c", line 267: warning: implicit function declaration: RAND_write_file
* "./nrpe.c", line 277: warning: implicit function declaration: RAND_seed
* "./nrpe.c", line 317: warning: implicit function declaration: ERR_get_error
* "./nrpe.c", line 319: warning: implicit function declaration: ERR_error_string
* "./nrpe.c", line 1752: warning: implicit function declaration: ERR_get_error_line_data
* "./nrpe.c", line 1754: warning: implicit function declaration: ERR_reason_error_string

missing includes in include/common.h:

```
#include <openssl/err.h>
#include <openssl/rand.h>
```

* "./nrpe.c", line 2156: warning: initializer will be sign-extended: -1
* "./nrpe.c", line 2157: warning: initializer will be sign-extended: -1

```
  2156          uid_t     uid = -1;
  2157          gid_t     gid = -1;
```

uid_t and gid_t are unsigned on Solaris:

```
grep uid_t /usr/include/sys/types.h

typedef unsigned int uid_t;             /* UID type             */
typedef uid_t   gid_t;                  /* GID type             */
```

* "./nrpe.c", line 2385: warning: statement not reached
* "./nrpe.c", line 2683: warning: statement not reached
* "./nrpe.c", line 2013: Warning: Likely out-of-bound read: *(output[1035]) in function my_system

No idea...


* "./acl.c", line 79: warning: statement not reached
* "./acl.c", line 82: warning: statement not reached
* "./acl.c", line 85: warning: statement not reached
* "./acl.c", line 88: warning: statement not reached

No idea

* "./check_nrpe.c", line 60: warning: initializer does not fit or is out of range: 2147486719

```
    60  int ssl_opts = SSL_OP_ALL;
```

Same as nrpe.c, s/int/long/.

* "./check_nrpe.c", line 305: warning: statement not reached
* "./check_nrpe.c", line 314: warning: statement not reached
* "./check_nrpe.c", line 451: warning: statement not reached

No idea

* "./check_nrpe.c", line 924: warning: implicit function declaration: ERR_get_error_line_data
* "./check_nrpe.c", line 926: warning: implicit function declaration: ERR_reason_error_string

Missing openssl include, see above

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/082527d4bd6946163829cf62357368b4a94d2c82

I opened new issue #75 to deal with the compiler warnings.
