### ISSUE TITLE
check_nrpe ignores -a option when -f option is specified

### ISSUE THREAD

**Issue by CombatZAK** [NagiosEnterprises/nrpe#69]
This seems like a somewhat obscure problem that _might_ be related to running against NSClient++, but the behavior seems entirely enclosed within check_nrpe. Here is my environment:

OS: CentOS 7
Nagios Version: 5.3.0
check_nrpe plugin version: 3.0.1
OpenSSL version: 1.0.1e

I am using a config file with the following options as part of my test:

`-A {path to ca_cert.pem}
-C {path to client_cert.pem}
-K {path to client_cert.key}`

When I use this file with the **-f** option, check_nrpe appears to ignore the **-a** option, if also provided.  For example, executing this command...

`./check_nrpe -H {remote_nscp_host} -f {path to config-file} -c check_cpu -a "warn=load > 85" "crit=load > 95"`

returns the following response:

`OK: CPU load is ok.|'total 5m'=0%;80;90 'total 1m'=0%;80;90 'total 5s'=0%;80;90`
(note that the warn and critical thresholds are 80% and 90% respectively, not 85% and 95% as specified by the arguments)

However, when I _don't_ use the config file, and instead specify my certificate paths in the command itself, the behavior is different.

Command:

`./check_nrpe -H {remote_nscp_host} -A {path to ca_cert.pem} -C {path to client_cert.pem} -K {path to client_cert.key} -c check_cpu -a "warn=load > 85" "crit=load > 95"`

Response:

`OK: CPU load is ok.|'total 5m'=0%;85;95 'total 1m'=0%;85;95 'total 5s'=0%;85;95`
(observe that the warn and crit thresholds are 85% and 95% respectively, as specified by the arguments)

The takeaway is that, regardless of what's going on with NSClient++ on the remote host, it appears very likely that the check_nrpe plugin on the nagios server is treating the -a option differently if the -f option is provided.

**Comment by box293** [comment]
I can confirm the problem you are reporting.

On a NRPE v3 client, I have the following command defined:

```
command[check_users_test]=/usr/local/nagios/libexec/check_users $ARG1$
```


Without the config file:
```
/usr/local/nagios/libexec/check_nrpe -A /usr/local/nagios/etc/ssl/ca/ca_cert.pem -C /usr/local/nagios/etc/ssl/nagios_server_certs/nagios_server.pem -K /usr/local/nagios/etc/ssl/nagios_server_certs/nagios_server.key -H 127.0.0.1 -c check_users_test -a '-w 5 -c 10'

USERS OK - 1 users currently logged in |users=1;5;10;0
```

With the config file:

```
/usr/local/nagios/libexec/check_nrpe -f /usr/local/nagios/etc/check_nrpe.config -H 127.0.0.1 -c check_users_test -a '-w 5 -c 10'


Usage:
check_users -w <users> -c <users>
```

So it appears to be an issue with the check_nrpe plugin.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/0e596e1170fc1dce96fdcfa9fa77c77e849a9ba2
