### ISSUE TITLE
nasty_metachars in configuration file

### ISSUE THREAD

**Issue by garnier-quentin** [NagiosEnterprises/nrpe#70]
Hi,

Right now, nasty_metachars is configured in 'nrpe.c'. Could you add an option in 'nrpe.cfg' to override the harded configuration ?

Thanks for the work.

**Comment by awiddersheim** [comment]
Sounds like you want some of the stuff done in https://github.com/NagiosEnterprises/nrpe/pull/6 but never merged.

**Comment by garnier-quentin** [comment]
Exactly :)

**Comment by jfrickson** [comment]
https://github.com/NagiosEnterprises/nrpe/pull/6 was merged, but @abrist never did a pull request from that repository. I'll look over those changes and see about either doing a merge, or incorporating them here.

**Comment by sebastic** [comment]
There is a patch floating around the web for this, see:

 https://support.nagios.com/forum/viewtopic.php?f=34&t=16496&sid=58980c1b98e69cbc2f05c43d27f0d04b
 https://lists.icinga.org/pipermail/icinga-checkins/2011-November/012778.html

This feature has also been requested in [Debian Bug #691328](https://bugs.debian.org/691328).

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/04cef56c472a3e6c81e7eafa094e3f9f1f125ec5
