### ISSUE TITLE
add -- option system with check_nrpe

### ISSUE THREAD

**Issue by garnier-quentin** [NagiosEnterprises/nrpe#71]
Hi,

I would like to use option in -a argument like that:
```
/usr/local/nagios/libexec/check_nrpe -2 -P 8192 -H 10.50.1.15 -c check_cpu -a --foo
```

Something like. I don't know if it's working and you can attach next values to "-a" argument:
```
/usr/local/nagios/libexec/check_nrpe -2 -P 8192 -H 10.50.1.15 -c check_cpu -a -- --foo test --test2
``` 

Thanks

**Comment by jfrickson** [comment]
That should work with no problems at all. Post another message here if you are having any problems.

**Comment by garnier-quentin** [comment]
Thanks. With which branch can i test it ?

**Comment by jfrickson** [comment]
You should be able to test with just about any branch. But `maint` has a minor fix you might need.
