### ISSUE TITLE
NRPE Main License

### ISSUE THREAD

**Issue by Alex-Vaduva** [NagiosEnterprises/nrpe#73]
Hello,

Can you please specified which is the main license for nrpe?
On the following site https://exchange.nagios.org/directory/Addons/Monitoring-Agents/NRPE--2D-Nagios-Remote-Plugin-Executor/details it's stated that the main license ins GPL. But the version isn't specified (1.0, 2.0 or 3.0).
Also in the package I didn't find the COPYING with the GPL full listed which is a required by the GPL-1.0, 2.0 or 3.0.

Alex

**Comment by jfrickson** [comment]
LICENSE file has been added in the 'maint' branch.

**Comment by Alex-Vaduva** [comment]
Thanks!
