### ISSUE TITLE
Compiler Warnings using Oracle Developer Studio on Solaris

### ISSUE THREAD

**Issue by jfrickson** [NagiosEnterprises/nrpe#75]
**_skrueger8 commented in issue #68 about compiler warnings. Opening a new issue for this._**

there are some compiler warnings though (I'm building with Oracle Developer Studio 12.5):

* "./nrpe.c", line 241: warning: initializer does not fit or is out of range: 2148535295

   241          int       ssl_opts = SSL_OP_ALL | SSL_OP_SINGLE_DH_USE, vrfy;

ssl_opts has to be long, not int; see man SSL_CTX_set_options:
```
OpenSSL                                          SSL_CTX_set_options(3openssl)

NAME
       SSL_CTX_set_options, SSL_set_options, SSL_CTX_clear_options,
       SSL_clear_options, SSL_CTX_get_options, SSL_get_options,
       SSL_get_secure_renegotiation_support - manipulate SSL options

SYNOPSIS
        #include <openssl/ssl.h>

        long SSL_CTX_set_options(SSL_CTX *ctx, long options);
```

* "./nrpe.c", line 264: warning: implicit function declaration: RAND_status
* "./nrpe.c", line 265: warning: implicit function declaration: RAND_file_name
* "./nrpe.c", line 266: warning: implicit function declaration: RAND_load_file
* "./nrpe.c", line 267: warning: implicit function declaration: RAND_write_file
* "./nrpe.c", line 277: warning: implicit function declaration: RAND_seed
* "./nrpe.c", line 317: warning: implicit function declaration: ERR_get_error
* "./nrpe.c", line 319: warning: implicit function declaration: ERR_error_string
* "./nrpe.c", line 1752: warning: implicit function declaration: ERR_get_error_line_data
* "./nrpe.c", line 1754: warning: implicit function declaration: ERR_reason_error_string

missing includes in include/common.h:
```
#include <openssl/err.h>
#include <openssl/rand.h>
```

* "./nrpe.c", line 2156: warning: initializer will be sign-extended: -1
* "./nrpe.c", line 2157: warning: initializer will be sign-extended: -1

```
  2156          uid_t     uid = -1;
  2157          gid_t     gid = -1;
```

uid_t and gid_t are unsigned on Solaris:
```
grep uid_t /usr/include/sys/types.h

typedef unsigned int uid_t;             /* UID type             */
typedef uid_t   gid_t;                  /* GID type             */
```
* "./nrpe.c", line 2385: warning: statement not reached
* "./nrpe.c", line 2683: warning: statement not reached
* "./nrpe.c", line 2013: Warning: Likely out-of-bound read: *(output[1035]) in function my_system

No idea...

* "./acl.c", line 79: warning: statement not reached
* "./acl.c", line 82: warning: statement not reached
* "./acl.c", line 85: warning: statement not reached
* "./acl.c", line 88: warning: statement not reached

No idea

* "./check_nrpe.c", line 60: warning: initializer does not fit or is out of range: 2147486719
```
60  int ssl_opts = SSL_OP_ALL;
```
Same as nrpe.c, s/int/long/.

* "./check_nrpe.c", line 305: warning: statement not reached
* "./check_nrpe.c", line 314: warning: statement not reached
* "./check_nrpe.c", line 451: warning: statement not reached

No idea

* "./check_nrpe.c", line 924: warning: implicit function declaration: ERR_get_error_line_data
* "./check_nrpe.c", line 926: warning: implicit function declaration: ERR_reason_error_string

Missing openssl include, see above

**Comment by jfrickson** [comment]
@skrueger8 I put fixes in the 'maint' branch. Can you download that and check it out?

**Comment by skrueger8** [comment]
I'm not getting very far with maint:

```
gmake[1]: Entering directory '/tmp/nrpe-maint/src'                                                            cc -m64 -Wall -xO4 -xarch=sparcvis2 -Qoption cg -xregs=no%appl -W2,-xwrap_int -xc99=all -xmemalign=16s -mt -KPIC -DPIC -I/usr/include/openssl -DHAVE_CONFIG_H -I ../include -I ./../include -o nrpe ./nrpe.c ./utils.c ./acl.c -m64 -zaslr=enable -M /usr/lib/ld/map.noexstk -M /usr/lib/ld/map.noexbss -M /usr/lib/ld/map.pagealign -Bdirect -zignore -zstrip-class=comment -L/usr/lib  -lssl -lcrypto -lnsl -lsocket
./nrpe.c:
"./nrpe.c", line 2399: warning: statement not reached
"./nrpe.c", line 2027: Warning: Likely out-of-bound read: *(output[1035]) in function my_system
./utils.c:
"./utils.c", line 249: undefined symbol: _PATH_STDPATH
"./utils.c", line 249: warning: improper pointer/integer combination: op "="
"./utils.c", line 249: non-constant initializer involving a cast
cc: acomp failed for ./utils.c
./acl.c:
"./acl.c", line 143: undefined symbol: TRUE
"./acl.c", line 159: undefined symbol: TRUE
"./acl.c", line 259: undefined symbol: TRUE
"./acl.c", line 470: undefined symbol: TRUE
"./acl.c", line 503: undefined symbol: TRUE
"./acl.c", line 512: undefined symbol: TRUE
"./acl.c", line 545: undefined symbol: TRUE
"./acl.c", line 554: undefined symbol: TRUE
"./acl.c", line 606: undefined symbol: TRUE
"./acl.c", line 622: undefined symbol: TRUE
"./acl.c", line 628: undefined symbol: TRUE
cc: acomp failed for ./acl.c
gmake[1]: *** [Makefile:48: nrpe] Error 2
gmake[1]: Leaving directory '/tmp/nrpe-maint/src'
```

I can fix this by adding `#include "../include/common.h"` to src/acl.h but then I got stuck again with:

```
./utils.c:
"./utils.c", line 249: undefined symbol: _PATH_STDPATH
"./utils.c", line 249: warning: improper pointer/integer combination: op "="
"./utils.c", line 249: non-constant initializer involving a cast
```

Seems like `_PATH_STDPATH` is not available on Solaris 11 and 12:

```
$ ggrep -r _PATH_STDPATH /usr/include/
$
```

**Comment by jfrickson** [comment]
More updates via commit https://github.com/NagiosEnterprises/nrpe/commit/4a88099e4311c13e50a9be24b8aa67837f4e22e8

Now you should only get `./nrpe.c", line 2027: Warning: Likely out-of-bound read: *(output[1035]) in function my_system`

**Comment by skrueger8** [comment]
You're right,

```
"./nrpe.c", line 2027: Warning: Likely out-of-bound read: *(output[1035]) in function my_system
```

is the only warning left now.

Good work.

**Comment by jfrickson** [comment]
It's a really minor warning, so at this point I'm not going to worry about it ;-)
