### ISSUE TITLE
nrpe 3.0.1 segfaults when key and/or cert are broken symlinks.

### ISSUE THREAD

**Issue by Houlistonm** [NagiosEnterprises/nrpe#76]
I think the application should display an error message to stderr/stdout and exit.
OS: RHEL5
Let me know if you need additional information.

**Comment by jfrickson** [comment]
In my `nrpe.cfg` file I have:
```
ssl_cert_file=/usr/local/nagios/etc/ssl/server_certs/server.pem
ssl_privatekey_file=/usr/local/nagios/etc/ssl/server_certs/server.key
```
Listing of the directory:
```
# ls -l /usr/local/nagios/etc/ssl/server_certs/
total 12
-rw-r--r-- 1 root root 1078 Dec 21  2015 db_server.csr
-rw-r--r-- 1 root root 1704 Dec 21  2015 db_server.key
-rw-r--r-- 1 root root 1874 Dec 21  2015 db_server.pem
lrwxrwxrwx 1 root root   13 Dec  5 13:26 server.csr -> db_server.csr
lrwxrwxrwx 1 root root   13 Dec  5 13:26 server.key -> db_server.key
lrwxrwxrwx 1 root root   13 Dec  5 13:26 server.pem -> db_server.pem
```
I ran the command:
```
$ ./check_nrpe -H 127.0.0.1 -c check_users
```
and received no segfault. 
```
$ openssl version
OpenSSL 1.0.1k-fips 8 Jan 2015

$ src/nrpe -V

NRPE - Nagios Remote Plugin Executor
Copyright (c) 1999-2008 Ethan Galstad (nagios@nagios.org)
Version: 3.0.1
Last Modified: 09-08-2016
```
Please provide any additional information you can think of that will help me reproduce the segfault.

**Comment by Houlistonm** [comment]
I running openssl 1.0.2h on a RHEL5 host.
I'll post additional details tomorrow when i'm back to the office.
Thanks.

**Comment by jfrickson** [comment]
By the way, here are the log messages I got:
```
Dec  5 14:42:06 localhost nrpe[10697]: Error: could not use certificate file /usr/local/nagios/etc/ssl/server_certs/server.pem : error:2D06C06E:FIPS routines:FIPS_module_mode_set:fingerprint does not match
Dec  5 14:42:06 localhost nrpe[10697]: Error: could not use certificate file /usr/local/nagios/etc/ssl/server_certs/server.pem : error:02001002:system library:fopen:No such file or directory
Dec  5 14:42:06 localhost nrpe[10697]: Error: could not use certificate file /usr/local/nagios/etc/ssl/server_certs/server.pem : error:20074002:BIO routines:FILE_CTRL:system lib
Dec  5 14:42:06 localhost nrpe[10697]: Error: could not use certificate file /usr/local/nagios/etc/ssl/server_certs/server.pem : error:140AD002:SSL routines:SSL_CTX_use_certificate_file:system lib
Dec  5 14:42:06 localhost check_nrpe: Error: Could not complete SSL handshake with 127.0.0.1: rc=0 SSL-error=5
```

**Comment by Houlistonm** [comment]
I had to re-type this, we don't have direct access to the internet from this system.
Our SSL Cipher string is the same string we use on our apache httpd 2.4.x servers.  

nrpe -d -c nrpe.cfg produces 

Dec  6 05:42:33 localhost nrpe[45676]: SSL Certificate File: /home/monitor/.certs/cert.pem
Dec  6 05:42:33 localhost nrpe[45676]: SSL Private Key File: /home/monitor/.certs/cert.key
Dec  6 05:42:33 localhost nrpe[45676]: SSL CA Certificate File: /software/CERTS/trustedCA.pem
Dec  6 05:42:33 localhost nrpe[45676]: SSL Cipher List: ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD4:!DSS
Dec  6 05:42:33 localhost nrpe[45676]: SSL Allow ADH: No
Dec  6 05:42:33 localhost nrpe[45676]: SSL Client Certs: Require
Dec  6 05:42:33 localhost nrpe[45676]: SSL Log Options: 0x2f
Dec  6 05:42:33 localhost nrpe[45676]: SSL Version: TLSv1_2
Dec  6 05:42:33 localhost kernel: nrpe[45676]: segfault at 00000000c6e91080 rip 00002ab4c7338ca0 rsp 0000f777d4182338 error 42

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/e4ae64e3ac8d72f26323aa781adbc84c7256c599.

See the commit message for an explanation, if you're interested.
