### ISSUE TITLE
nrpe 3.0.1 allows TLSv1 and TLSv1.1 when I configure for TLSv1.2+

### ISSUE THREAD

**Issue by Houlistonm** [NagiosEnterprises/nrpe#77]
I use a ssltest.sh (https://testssl.sh) to scan the nrpe after configuring and starting.
Testssl.sh reports TLSv1, TLSv1.1, and TLSv1.2 when TLSv1.2+ is specified in the nrpe.cfg. 
Testssl.sh report TLSv1.2 when TLSv1.2 is specified in the nrpe.cfg

nrpe is configured to require certs.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/aec3eee982ef2ae19ad60f01466771d60908ced4
