### ISSUE TITLE
Enhancement: request support for cipher order on nrped.

### ISSUE THREAD

**Issue by Houlistonm** [NagiosEnterprises/nrpe#79]
SSL_OP_CIPHER_SERVER_PREFERENCE
    When choosing a cipher, use the server's preferences instead of the client preferences. When not set, the SSL server will always follow the clients preferences. When set, the SSLv3/TLSv1 server will choose following its own preferences. Because of the different protocol, for SSLv2 the server will send its list of preferences to the client and the client chooses.

A configuration item to enable / disable this openssl feature would resolve an ssl configuration testing result.

(using the testssl.sh test tool).

**Comment by jfrickson** [comment]
Looking into this

**Comment by jfrickson** [comment]
Since `check_nrpe` is the client, and runs on the nagios server, it should be the primary decider, even though it's technically the client.
