### ISSUE TITLE
nrpe 3.0.1 appears to be vulnerable to client initiated renegotiation DOS threat.

### ISSUE THREAD

**Issue by Houlistonm** [NagiosEnterprises/nrpe#81]
testssl.sh is reporting/alerting that nrpe 3.0.1 is vulnerable to Secure Client Initiated Renegotiation (DOS Treat). 
It is my understanding that security scanners/testers prefer for the clients to not accept/allow Client Initiated Renegotiations. 

Our security scans are reporting this issue for nrped but not for Apache httpd, and both use the same version of openssl (1.0.2h) - so I'm ASSUMING it is a configuration of openssl.

**Comment by jfrickson** [comment]
Looking into this

**Comment by jfrickson** [comment]
If I understand correctly, OpenSSL 0.9.8m and above will always do secure renegotiation. So `VULNERABLE` (in yellow) is not a problem.

Or do I misunderstand?

**Comment by jfrickson** [comment]
No response for 6 weeks. Closing.
