### ISSUE TITLE
Return UNKNOWN when check_nrpe cannot communicate with nrpe

### ISSUE THREAD

**Issue by sebastic** [NagiosEnterprises/nrpe#85]
As reported by Michael Bussmann in [Debian Bug #445976](https://bugs.debian.org/445976):
> While check_nrpe has a "-u" option to return UNKNOWN (instead of CRITICAL) when a socket timeout occurs, it sometimes still returns CRITICAL, when there are errors in opening the connection in my_connect().
> 
> As we don't know anything about the result of the checks if the host cannot be reached, I think it's better to return UNKNOWN instead of CRITITCAL.
> 
> Another option would be to return timeout_return_code (thus honoring -u).

**Comment by jfrickson** [comment]
Looking into this

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/aa182283756b5b687c6b2c8e117e7f965e57ee15
