### ISSUE TITLE
Same return code for "plugin not found" and "status critical"

### ISSUE THREAD

**Issue by sebastic** [NagiosEnterprises/nrpe#86]
As reported by Michael Banck in [Debian Bug #565643](https://bugs.debian.org/565643):
> If a NRPE client requests a check for a plugin/command which is not configured in nrpe*.cfg, the same return code (2) as for a critical service status is returned:
> 
> ```
> Jan 17 17:09:46 raptor nrpe[25208]: Return Code: 2, Output: DISK CRITICAL - free space: /usr 0 MB (0% inode=34%);| /usr=3717MB;3003;3378;0;3754
> Jan 17 17:09:46 raptor nrpe[25217]: Return Code: 2, Output: NRPE: Command 'check_foo' not defined
> ```
> 
> This is unfortunate, for example it is not possible to reliably check a remote NRPE server for which checks it supports, as the return values for services in critical state would be ommitted.
> 
> I think it would make more sense to return the error code (3, STATE_UNKNOWN) in the case of a non-configured check, or possibly assign a different error code alltogether for this case..

**Comment by jfrickson** [comment]
We'll have to discuss this internally.

**Comment by jfrickson** [comment]
This is considered a fairly major functionality change, so it's being scheduled for NRPE 4.

**Comment by garnier-quentin** [comment]
It could be nice. Moreover, it could be great to have an option in check_nrpe to write in stdout instead of stderr.

**Comment by hedenface** [comment]
@garnier-quentin Can you open a separate issue for your request, please? I think that is a good idea, as well.

**Comment by garnier-quentin** [comment]
@hedenface it's done: https://github.com/NagiosEnterprises/nrpe/issues/132

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nrpe/commit/f4ee3eb67e1b5e91f6539c5995b63f6729224801
