### ISSUE TITLE
rpmbuild fail to read the nrpe-3.0.1.tar.gz spec file

### ISSUE THREAD

**Issue by alteg0** [NagiosEnterprises/nrpe#87]
While trying to build a rpm file from nrpe-3.0.1.tar.gz on Centos 7, rpmbuild -ta command fails with the message: "error: Failed to read spec file from nrpe-3.0.1.tar.gz"

**Comment by jfrickson** [comment]
The `nrpe.spec` file is created during `./configure` from `nrpe.spec.in`. Run a configure then rebuild the tarball with the new `nrpe.spec` file included.
