### ISSUE TITLE
xinetd.d parameter causes many messages in log file

### ISSUE THREAD

**Issue by MyCatHasEyes** [NagiosEnterprises/nrpe#88]
Suggestion:
In the /etc/xinetd.d/nrpe file.
When you use "log_on_failure  += USERID" you get 2 line items in the messages file every time the binary gets invoked. This causes the messages file to have many non value added lines.

Instead, use this in the file
"log_on_success ="

I have made this change on all my systems and the log file data becomes more readable.
Thanks.
Steve B

**Comment by jfrickson** [comment]
Sounds reasonable. Looking into it.

**Comment by jfrickson** [comment]
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/76558a424ff7035875a16c670a6a2d65b8007a26
