### ISSUE TITLE
NRPE Bug: It sends two RST flags

### ISSUE THREAD

**Issue by abrist** [NagiosEnterprises/nrpe#9]
Import from the forums:  http://support.nagios.com/forum/viewtopic.php?t=28250#105778

As you can read at this two URLS:

http://tracker.nagios.org/view.php?id=305
and
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=744936

nrpe is sending two RST flags and for us that means that every query via nrpe causes an error in our firewall installed on the nagios server.
Would it be possible to fix this in a future version? So that it may will be fixed in a future debian version?

**Comment by jfrickson** [comment]
Patch by Jari Takaala implemented end of 2014. No further reports since then. Considering this issue closed.
