### ISSUE TITLE
Can´t receive data from remote NRPE on Debian/Ubuntu

### ISSUE THREAD

**Issue by PetrMa** [NagiosEnterprises/nrpe#92]
Hello,
i have a problem with receiving of NRPE data from remote systems running on Debian or Ubuntu. On remote CentOS it is OK.

I have installed NRPE on my remote servers by manual on http://tecadmin.net/install-nrpe-on-ubuntu/.
After installation I changed only htse parameters:
**allowed_hosts=127.0.0.1, 172.30.0.26
dont_blame_nrpe=1
and all hardcoded command were commented and user-supplied arguments commands were enabled.**

Command **./check_nrpe -H 172.31.0.239** from my Nagios server receives **NRPE v2.15** from remote server.

If I use the command for ex.
**./check_nrpe -H 172.31.0.239 -c check_disk -a 20% 10% /**
then I received this error from check_nrpe 2.15:
**CHECK_NRPE: Received 0 bytes from daemon.  Check the remote server logs for error messages.**
from check_nrpe 3.0.1:
**CHECK_NRPE: Receive header underflow - only 0 bytes received (4 expected).**

If i disable on remote server in nrpe.cfg user-supplied arguments commands and enable hardcoded commands then i receive right data on Nagios server for ex. command:
**./check_nrpe -H 172.31.0.239 -c check_disk
DISK OK - free space: / 7467 MB (73% inode=75%);| /=2659MB;8540;9607;0;10675**

Whats worng? Can anyone help me with this issue please? I would like to use user-argument commands.

thanks, Petr

**Comment by box293** [comment]
From what I understand, when you install nrpe via apt-get, the --enable-command-args flag is not provided as part of the compile and hence you cannot provide arguments.

The following guide shows you how to install it from source to overcome these issues:
https://support.nagios.com/kb/article.php?id=515

**Comment by jfrickson** [comment]
Troy's answer above is correct. It's a configuration parameter. Closing.
