### ISSUE TITLE
rpmbuild -ta nrpe-3.0.1.tar.gz failed File not found: /etc/init.d/nrpe

### ISSUE THREAD

**Issue by rcanete** [NagiosEnterprises/nrpe#94]
OS = RHEL6.6 64bit

Created the nrpe.spec using below commands: 
./configure --with-opsys=linux --with-dist-type=rh --with-inetd-type=xinetd --with-init-type=sysv --enable-install-method=os

and add it in the tar file.

When I tried run rpmbuild it give errors.

rpmbuild -ta nrpe-3.0.1.tar.gz

ake[1]: Entering directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
make install-plugin
make[2]: Entering directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
/usr/bin/install -c -m 755 -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin
/usr/bin/install -c -m 755 ../uninstall /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin/nrpe-uninstall
/usr/bin/install -c -m 775 -o nagios -g nagios -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/lib/nagios/plugins
/usr/bin/install -c -m 775 -o nagios -g nagios -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/lib/nagios/plugins
/usr/bin/install -c -m 775 -o nagios -g nagios check_nrpe /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/lib/nagios/plugins
make[2]: Leaving directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
make install-daemon
make[2]: Entering directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
/usr/bin/install -c -m 755 -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin
/usr/bin/install -c -m 755 ../uninstall /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin/nrpe-uninstall
/usr/bin/install -c -m 755 nrpe /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin
/usr/bin/install -c -m 755 -o nagios -g nagios -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/var/log/nagios
make[2]: Leaving directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
make[1]: Leaving directory `/root/rpmbuild/BUILD/nrpe-3.0.1/src'
/usr/bin/install -c -m 775 -o nagios -g nagios -d /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/nagios
/usr/bin/install -c -m 644 -o nagios -g nagios sample-config/nrpe.cfg /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/nagios
/usr/bin/install -c -m 644 startup/rh-upstart-init /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init/nrpe.conf
/usr/bin/install: cannot create regular file `/root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init/nrpe.conf': No such file or directory
initctl reload-configuration
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id /root/rpmbuild/BUILD/nrpe-3.0.1
extracting debug info from /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/sbin/nrpe
extracting debug info from /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/lib/nagios/plugins/check_nrpe
308 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: nrpe-3.0.1-1.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init.d/nrpe
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/nagios
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.Kwf77u
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd nrpe-3.0.1
+ DOCDIR=/root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1
+ export DOCDIR
+ rm -rf /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1
+ /bin/mkdir -p /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1
+ cp -pr Changelog LEGAL README.md README.SSL.md SECURITY.md /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1
+ exit 0
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1

RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init.d/nrpe
    %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/nagios
    %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/usr/share/doc/nrpe-3.0.1

Please help.

Best regards,

**Comment by bvandi** [comment]
I have the same issues. Looks like the offending is: 
```
/usr/bin/install -c -m 644 startup/rh-upstart-init /root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init/nrpe.conf
/usr/bin/install: cannot create regular file `/root/rpmbuild/BUILDROOT/nrpe-3.0.1-1.x86_64/etc/init/nrpe.conf': No such file or directory

```

The Makefile in the BUILD area has INIT_DIR=$(DESTDIR)/etc/init 

Also seeing an issue with: 
```
+ ./configure --with-init-dir=/etc/init.d --with-nrpe-port=5666 --with-nrpe-user=nagios --with-nrpe-group=nagios --prefix=/usr --exec-prefix=/usr/sbin --bindir=/usr/sbin --sbindir=/usr/lib/nagios/cgi --libexecdir=/usr/lib/nagios/plugins --datadir=/usr/share/nagios --sysconfdir=/etc/nagios --localstatedir=/var/log/nagios --enable-command-args
configure: WARNING: unrecognized options: --with-init-dir
```

When I use this command in the source tree outside of the rpmbuild, I yield the same results.

I changed the nrpe.spec file from referencing _init_dir /etc/init to init_type svsv.  Also the Makefile needs to be modified that it does not perform the chkconfig command. 

I have included the two files that I modified for review (Makefile.in and nrpe.spec.in)
[nrpe301rpm_build_issue94.zip](https://github.com/NagiosEnterprises/nrpe/files/797229/nrpe301rpm_build_issue94.zip)

**Comment by jfrickson** [comment]
Thanks for the modified files. I'll be looking into this soon.

**Comment by jfrickson** [comment]
Should be fixed in branch `maint` now via commit https://github.com/NagiosEnterprises/nrpe/commit/a9374448d481f9f8b9ae65965a24ef1d7c7ba534

Let me know if there's still a problem.
