### ISSUE TITLE
Segfault with ssl_cert_file in Debian Stretch

### ISSUE THREAD

**Issue by rubaoliva** [NagiosEnterprises/nrpe#95]
DEBIAN                        = stretch
nagios-nrpe-server      = 3.0.1
nagios-nrpe-plugin       = 3.0.1

When i try start the nrpe-server daemon with "ssl_cert_file" in /etc/nagios/nrpe.cfg, have the following out in /var/log/syslog

---------------------------------
nrpe[4501]: SSL Certificate File: /usr/local/SacUtils/nagios/etc/ssl/server_certs/db_server.pem
nrpe[4501]: SSL Private Key File: /usr/local/SacUtils/nagios/etc/ssl/server_certs/db_server.key
nrpe[4501]: SSL CA Certificate File: /usr/local/SacUtils/nagios/ca/cacert.pem
nrpe[4501]: SSL Cipher List: ALL:!MD5:@STRENGTH
nrpe[4501]: SSL Allow ADH: No
nrpe[4501]: SSL Client Certs: Don't Ask
nrpe[4501]: SSL Log Options: 0xffffffff
nrpe[4501]: SSL Version: TLSv1_2 And Above
kernel: [19747.184231] nrpe[4501]: segfault at 6be64a08 ip 00007f646b2c4496 sp 00007fff973c87c8 error 4 in libc-2.24.so[7f646b244000+195000]
nrpe[5383]: SSL Cipher List: ALL:!MD5:@STRENGTH
nrpe[5383]: SSL Allow ADH: No
nrpe[5383]: SSL Client Certs: Don't Ask
nrpe[5383]: SSL Log Options: 0xffffffff
nrpe[5383]: SSL Version: TLSv1_2 And Above
systemd[1]: nagios-nrpe-server.service: Main process exited, code=killed, status=11/SEGV
systemd[1]: nagios-nrpe-server.service: Unit entered failed state.
systemd[1]: nagios-nrpe-server.service: Failed with result 'signal'.
systemd[1]: nagios-nrpe-server.service: Service hold-off time over, scheduling restart.
systemd[1]: Stopped Nagios Remote Plugin Executor.

------------------------------------------------

If remove "ssl_cert_file" in /etc/nagios/nrpe.cfg everything run ok but i can't make ssl conections

-------------------------------------------

nrpe[4572]: SSL Certificate File: None
nrpe[4572]: SSL Private Key File: /usr/local/SacUtils/nagios/etc/ssl/server_certs/db_server.key
nrpe[4572]: SSL CA Certificate File: /usr/local/SacUtils/nagios/ca/cacert.pem
nrpe[4572]: SSL Cipher List: ALL:!MD5:@STRENGTH
nrpe[4572]: SSL Allow ADH: No
nrpe[4572]: SSL Client Certs: Don't Ask
nrpe[4572]: SSL Log Options: 0xffffffff
nrpe[4572]: SSL Version: TLSv1 And Above
nrpe[4572]: INFO: SSL/TLS initialized. All network traffic will be encrypted.
nrpe[4572]: Starting up daemon
nrpe[4572]: Server listening on 0.0.0.0 port 5666.
nrpe[4572]: Server listening on :: port 5666.
nrpe[4572]: Listening for connections on port 5666
nrpe[4572]: Allowing connections from: 127.0.0.1

-------------------------------------------

nrpe[5035]: Connection from 127.0.0.1 port 47303
nrpe[5035]: Host address is in allowed_hosts
kernel: [ 1556.667501] nrpe[5035]: segfault at b019ff9d ip 00007fadaf5a9496 sp 00007fff1c018338 error 4 in libc-2.24.so[7fadaf529000+195000]
check_nrpe: Error: Could not complete SSL handshake with 127.0.0.1: rc=-1 SSL-error=1

**Comment by rubaoliva** [comment]
Updated info with specific versions of packets in debian stretch

||/ Name           Version               Architecture                Description
+++-==============-============-============-=================================
ii  nagios-nrpe-se 3.0.1-3               amd64        Nagios Remote Plugin Executor Ser
ii  nagios-nrpe-plugin  3.0.1-3        amd64          Nagios Remote Plugin Executor Plugin
ii  openssl             1.1.0c-2             amd64          Secure Sockets Layer toolkit - cryptographic

**Comment by jfrickson** [comment]
Looking into it. Should have something before too long.

**Comment by jfrickson** [comment]
@rubaoliva This may be fixed in branch `maint`. Can you try it, please?

**Comment by rubaoliva** [comment]
@jfrickson Now everything works fine in Debian Stretch. Thank you. I hope Debian maintainers include this fix soon in the official packet. Thanks for your work.

**Comment by jfrickson** [comment]
Thanks for getting back so quickly!
