### ISSUE TITLE
PATH and other environment variables not set with numeric nrpe_user

### ISSUE THREAD

**Issue by mbunkus** [NagiosEnterprises/nrpe#96]
If the configuration variable `nrpe_user` is set to a numeric ID, then several environment variables (`PATH`, `IFS`, `HOME`, `SHELL`, `LOGNAME`, `USER`) are not set. The reason is that the new function `clean_environment` returns too early. To be more precise: it happens because the call to `getpwnam` fails with a numeric ID.

The result is that checks will have an environment that's too clean. For example, Perl scripts won't have a `PATH` they can operate on.

The issue disappears as soon as I set `nrpe_user` to a user name instead of a user ID. It's also an obvious regression from earlier versions (2.x) where said function simply didn't exist.

The resason why I'm using a numeric ID is that this is the default configuration on Arch Linux.

**Comment by jfrickson** [comment]
I just need to add a lookup by id. Should be pretty easy.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nrpe/commit/acda648d6c7818b626d3a1f9b8de2e2064b8c303

**Comment by mbunkus** [comment]
Thank you.
