### ISSUE TITLE
Redefinition of Checks

### ISSUE THREAD

**Issue by frankcrawford** [NagiosEnterprises/nrpe#97]
Currently nrpe handles the redefinition of checks more by accident than design, and currently has some places were the ordering is undefined.

Within a single configuration file, the last definition of a check is the one used, as it is closest to the head of the command list and the search stops at the first match found.

However, when multiple files are searched with an "include_dir" statement, the order is undefined, or more correctly, the order readdir returns. It would be good if this order were defined, preferably in alphabetical order, similar to ls.

**Comment by philfry** [comment]
Hi,

#98 should fix this :)

Kind regards

Philippe

**Comment by frankcrawford** [comment]
Yep, that looks like what I was suggesting.

Thanks
Frank

**Comment by jfrickson** [comment]
I'll probably be merging that PR soon. Just need to finish checking for cross-platform problems.

**Comment by jfrickson** [comment]
Commit https://github.com/NagiosEnterprises/nrpe/commit/25f49109ecad8acbc88de1077d3ba32e18b66814 should have it working now in the 'maint' branch. Please try it out and post a message here if there are any problems.

@philfry I used your pull request as a base, but made some changes. Thanks for posting it.
